---
- name: Prepare VM network and enable RHEL repositories
  hosts: localhost
  gather_facts: false

  vars:
    vm_name: "apache-vm"
    vm_namespace: "vm-migration-test"
    vm_ip: "10.0.0.118"          # Use exported VM IP from create-VM playbook
    rhsm_username: "info@pacetechsystems.com"
    rhsm_password: "Silverado@8787!!!!"
    rhel_version: 9
    repos_to_enable:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - codeready-builder-for-rhel-9-x86_64-rpms

  tasks:
    - name: Add VM to dynamic inventory
      add_host:
        name: "{{ vm_name }}"
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: password
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        groups: vms

    - name: Display added VM info
      debug:
        msg: "VM {{ vm_name }} ({{ vm_ip }}) added to dynamic group 'vms'"

- name: Configure network, verify connectivity, and register VM
  hosts: vms
  gather_facts: yes
  become: true

  vars:
    repos_to_enable:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - codeready-builder-for-rhel-9-x86_64-rpms
    registration_retries: 3
    registration_delay: 10
    network_check_retries: 10
    network_check_delay: 10

  tasks:
    # ============================================================
    # NETWORK CONFIGURATION
    # ============================================================
    - name: Ensure NetworkManager is installed
      package:
        name: NetworkManager
        state: present

    - name: Ensure NetworkManager service is running
      service:
        name: NetworkManager
        state: started
        enabled: true

    - name: Add DHCP connection for eth0 if it does not exist
      command: nmcli con add type ethernet ifname eth0 con-name eth0 dhcp yes
      args:
        creates: /etc/NetworkManager/system-connections/eth0.nmconnection

    - name: Set Google DNS for eth0
      command: nmcli con modify eth0 ipv4.dns "8.8.8.8 8.8.4.4"

    - name: Bring up eth0 connection
      command: nmcli con up eth0

    - name: Wait for network connectivity (ping 8.8.8.8)
      shell: ping -c 1 8.8.8.8
      register: ping_result
      retries: "{{ network_check_retries }}"
      delay: "{{ network_check_delay }}"
      until: ping_result.rc == 0
      ignore_errors: false

    # ============================================================
    # SUBSCRIPTION REGISTRATION AND REPO CONFIGURATION
    # ============================================================
    - name: Ensure subscription-manager is installed
      package:
        name: subscription-manager
        state: present

    - name: Unregister any existing registration
      shell: |
        subscription-manager remove --all || true
        subscription-manager unregister || true
        subscription-manager clean || true
      ignore_errors: true

    - name: Register the system with Red Hat Subscription Manager
      shell: |
        subscription-manager register \
          --username='{{ rhsm_username }}' \
          --password='{{ rhsm_password }}' \
          --auto-attach
      register: register_result
      retries: "{{ registration_retries }}"
      delay: "{{ registration_delay }}"
      until: register_result.rc == 0
      no_log: true

    - name: Wait for redhat.repo to appear
      wait_for:
        path: /etc/yum.repos.d/redhat.repo
        state: present
        timeout: 60

    - name: Disable all repos (clean start)
      shell: subscription-manager repos --disable="*"

    - name: Enable required RHEL repositories
      shell: "subscription-manager repos --enable={{ item }}"
      loop: "{{ repos_to_enable }}"

    - name: Install EPEL repository
      shell: |
        dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ rhel_version }}.noarch.rpm
      args:
        creates: /etc/yum.repos.d/epel.repo

    - name: Clean and refresh repo metadata
      shell: |
        dnf clean all
        dnf makecache

    - name: Verify repository access
      shell: dnf repolist enabled
      register: repolist
      changed_when: false

    - name: Display final enabled repositories
      debug:
        msg: "{{ repolist.stdout_lines }}"
