---
- name: Configure network and register VM with RHEL repositories
  hosts: apache-vm
  gather_facts: yes
  become: true

  vars:
    rhsm_username: "info@pacetechsystems.com"
    rhsm_password: "Silverado@8787!!!!"
    rhel_version: 9
    repos_to_enable:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - codeready-builder-for-rhel-9-x86_64-rpms
    cloud_dns: "8.8.8.8"

  tasks:

    - name: Ensure eth0 interface is up and configured via DHCP
      shell: dhclient -v eth0 || true

    - name: Ensure /etc/resolv.conf contains Google DNS
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: "nameserver {{ cloud_dns }}"
        state: present

    - name: Verify network connectivity
      command: ping -c 3 google.com
      register: ping_result
      retries: 5
      delay: 5
      until: ping_result.rc == 0

    - name: Ensure subscription-manager is installed
      package:
        name: subscription-manager
        state: present

    - name: Unregister any existing registration
      shell: |
        subscription-manager remove --all || true
        subscription-manager unregister || true
        subscription-manager clean || true
      ignore_errors: true

    - name: Register the system with Red Hat Subscription Manager
      shell: |
        subscription-manager register \
          --username='{{ rhsm_username }}' \
          --password='{{ rhsm_password }}' \
          --auto-attach
      register: register_result
      retries: 3
      delay: 10
      until: register_result.rc == 0
      no_log: true

    - name: Wait for redhat.repo to appear
      wait_for:
        path: /etc/yum.repos.d/redhat.repo
        state: present
        timeout: 60

    - name: Disable all repos (clean start)
      shell: subscription-manager repos --disable="*"

    - name: Enable required RHEL repositories
      shell: "subscription-manager repos --enable={{ item }}"
      loop: "{{ repos_to_enable }}"

    - name: Install EPEL repository
      shell: |
        dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ rhel_version }}.noarch.rpm
      args:
        creates: /etc/yum.repos.d/epel.repo

    - name: Clean and refresh repo metadata
      shell: |
        dnf clean all
        dnf makecache

    - name: Verify repository access
      shell: dnf repolist enabled
      register: repolist
      changed_when: false

    - name: Display final enabled repositories
      debug:
        msg: "{{ repolist.stdout_lines }}"
