---
- name: Register apache-vm and enable RHEL repositories
  hosts: localhost
  gather_facts: false

  vars:
    vm_name: "apache-vm"
    vm_namespace: "vm-migration-test"
    rhsm_username: "info@pacetechsystems.com"
    rhsm_password: "Silverado@8787!!!!"
    rhel_version: 9
    repos_to_enable:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - codeready-builder-for-rhel-9-x86_64-rpms
    registration_retries: 3
    registration_delay: 10

  tasks:
    - name: Get VM info from KubeVirt
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vm_info
      retries: 10
      delay: 5
      until: vm_info.resources | length > 0

    - name: Extract VM IPv4 address
      set_fact:
        vm_ip: >-
          {{
            (vm_info.resources[0].status.interfaces
            | selectattr('interfaceName','equalto','eth0')
            | list)[0].ipAddress
          }}

    - name: Fail if no IPv4 found
      fail:
        msg: "❌ No IPv4 address found for VM {{ vm_name }}. Guest agent may not be ready."
      when: vm_ip is not defined or vm_ip == ''

    - name: Display VM IP
      debug:
        msg: "✅ Found IPv4 for {{ vm_name }}: {{ vm_ip }}"

    - name: Add VM to dynamic inventory
      add_host:
        name: "{{ vm_name }}"
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: "password"   # matches your cloud-init
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        groups: vms

- name: Register system and enable repositories on apache-vm
  hosts: vms
  gather_facts: yes
  become: true

  vars:
    repos_to_enable:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - codeready-builder-for-rhel-9-x86_64-rpms
    registration_retries: 3
    registration_delay: 10

  tasks:
    - name: Ensure subscription-manager is installed
      package:
        name: subscription-manager
        state: present

    - name: Unregister any existing registration
      shell: |
        subscription-manager remove --all || true
        subscription-manager unregister || true
        subscription-manager clean || true
      ignore_errors: true

    - name: Register the system with Red Hat Subscription Manager (retry)
      shell: |
        subscription-manager register \
          --username='{{ rhsm_username }}' \
          --password='{{ rhsm_password }}' \
          --auto-attach
      register: register_result
      retries: "{{ registration_retries }}"
      delay: "{{ registration_delay }}"
      until: register_result.rc == 0
      no_log: true

    - name: Wait for redhat.repo to appear
      wait_for:
        path: /etc/yum.repos.d/redhat.repo
        state: present
        timeout: 60

    - name: Disable all repos (clean start)
      shell: subscription-manager repos --disable="*"

    - name: Enable required RHEL repositories
      shell: "subscription-manager repos --enable={{ item }}"
      loop: "{{ repos_to_enable }}"

    - name: Install EPEL repository
      shell: |
        dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ rhel_version }}.noarch.rpm
      args:
        creates: /etc/yum.repos.d/epel.repo

    - name: Clean and refresh repo metadata
      shell: |
        dnf clean all
        dnf makecache

    - name: Verify repository access
      shell: dnf repolist enabled
      register: repolist
      changed_when: false

    - name: Display final enabled repositories
      debug:
        msg: "{{ repolist.stdout_lines }}"
