---
- name: Add RHEL repositories to apache-vm
  hosts: localhost
  gather_facts: false

  vars:
    vm_name: "apache-vm"
    vm_namespace: "vm-migration-test"
    rhsm_username: "info@pacetechsystems.com"
    rhsm_password: "Silverado@8787!!!!"
    rhel_version: 9
    repos_to_enable:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - codeready-builder-for-rhel-9-x86_64-rpms

  tasks:
    - name: Get VM instance info from KubeVirt
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vmi_info
      retries: 10
      delay: 5
      until: (vmi_info.resources | default([])) | length > 0

    - name: Extract VM IP address (IPv4 preferred, fallback to IPv6)
      set_fact:
        vm_ip: >-
          {{
            (
              vmi_info.resources[0].status.interfaces[0].ipAddress 
              if vmi_info.resources[0].status.interfaces[0].ipAddress is defined
              else
              (vmi_info.resources[0].status.interfaces[0].ipAddresses[0] | default(''))
            )
          }}

    - name: Fail if no IP found
      fail:
        msg: "❌ No IP found for VM {{ vm_name }} in namespace {{ vm_namespace }}. Guest agent may not be ready."
      when: vm_ip == ""

    - name: Display discovered VM IP
      debug:
        msg: "✅ Using IP {{ vm_ip }} for VM {{ vm_name }}"

    - name: Add VM to dynamic inventory
      add_host:
        name: "{{ vm_name }}"
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: "{{ rhsm_password }}"
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
          {% if ':' in vm_ip %}-o AddressFamily=inet6{% endif %}
        groups: vms

- name: Register system and enable repositories on apache-vm
  hosts: vms
  gather_facts: yes
  become: true

  vars:
    repos_to_enable:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - codeready-builder-for-rhel-9-x86_64-rpms

  tasks:
    - name: Ensure subscription-manager is installed
      package:
        name: subscription-manager
        state: present

    - name: Unregister any existing registration
      shell: |
        subscription-manager remove --all || true
        subscription-manager unregister || true
        subscription-manager clean || true
      ignore_errors: true

    - name: Register the system with Red Hat Subscription Manager
      shell: |
        subscription-manager register \
          --username='{{ rhsm_username }}' \
          --password='{{ rhsm_password }}' \
          --auto-attach
      register: register_result
      retries: 3
      delay: 10
      until: register_result.rc == 0
      no_log: true

    - name: Wait for redhat.repo to appear
      wait_for:
        path: /etc/yum.repos.d/redhat.repo
        state: present
        timeout: 60

    - name: Disable all repos (clean start)
      shell: subscription-manager repos --disable="*"

    - name: Enable required RHEL repositories
      shell: "subscription-manager repos --enable={{ item }}"
      loop: "{{ repos_to_enable }}"

    - name: Install EPEL repository
      shell: |
        dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ rhel_version }}.noarch.rpm
      args:
        creates: /etc/yum.repos.d/epel.repo

    - name: Clean and refresh repo metadata
      shell: |
        dnf clean all
        dnf makecache

    - name: Verify repository access
      shell: dnf repolist enabled
      register: repolist
      changed_when: false

    - name: Display final enabled repositories
      debug:
        msg: "{{ repolist.stdout_lines }}"
