---
- name: Configure network, register VM, and enable RHEL repositories
  hosts: localhost
  gather_facts: false

  vars:
    vm_name: "apache-vm"
    vm_namespace: "vm-migration-test"
    vm_gateway: "10.0.0.1"
    vm_dns: "8.8.8.8"
    rhsm_username: "info@pacetechsystems.com"
    rhsm_password: "Silverado@8787!!!!"
    rhel_version: 9
    repos_to_enable:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - codeready-builder-for-rhel-9-x86_64-rpms
    max_ip_wait: 300
    ip_poll_interval: 10
    ssh_timeout: 300
    ansible_ssh_common_args: '-o AddressFamily=inet -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:
    - name: Fetch VM IPv4 from KubeVirt
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ vm_namespace }}"
        name: "{{ vm_name }}"
        validate_certs: no
      register: vmi_info
      until: 
        - vmi_info.resources | length > 0
        - vmi_info.resources[0].status.interfaces[0].ipAddress is defined
      retries: "{{ max_ip_wait // ip_poll_interval }}"
      delay: "{{ ip_poll_interval }}"

    - name: Set VM IP fact
      set_fact:
        vm_ip: "{{ vmi_info.resources[0].status.interfaces[0].ipAddress }}"

    - name: Add VM to dynamic inventory
      add_host:
        name: "{{ vm_name }}"
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: "password"
        ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"
        groups: vms

    - name: Display added VM info
      debug:
        msg: "VM {{ vm_name }} ({{ vm_ip }}) added to dynamic group 'vms'"

- name: Configure network and register RHEL system on VM
  hosts: vms
  become: true
  gather_facts: true

  tasks:
    - name: Ensure NetworkManager is installed
      package:
        name: NetworkManager
        state: present

    - name: Configure static network for eth0
      shell: |
        nmcli con delete eth0 || true
        nmcli con add type ethernet ifname eth0 con-name eth0 \
          ipv4.addresses {{ vm_ip }}/24 \
          ipv4.gateway {{ vm_gateway }} \
          ipv4.dns {{ vm_dns }} \
          ipv4.method manual autoconnect yes
        nmcli con up eth0
      register: nmcli_result

    - name: Wait for SSH port 22 to be available
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        timeout: "{{ ssh_timeout }}"
        state: started

    - name: Test DNS resolution
      command: ping -c 2 google.com
      register: ping_result
      ignore_errors: true

    - name: Display DNS test result
      debug:
        var: ping_result

    - name: Ensure subscription-manager is installed
      package:
        name: subscription-manager
        state: present

    - name: Clean old registration if any
      shell: |
        subscription-manager remove --all || true
        subscription-manager unregister || true
        subscription-manager clean || true
      ignore_errors: true

    - name: Register the system with Red Hat Subscription Manager
      shell: |
        subscription-manager register \
          --username='{{ rhsm_username }}' \
          --password='{{ rhsm_password }}' \
          --auto-attach
      register: register_result
      retries: 3
      delay: 10
      until: register_result.rc == 0
      no_log: false

    - name: Disable all repos (clean start)
      command: subscription-manager repos --disable="*"

    - name: Enable required RHEL repositories
      command: subscription-manager repos --enable="{{ item }}"
      loop: "{{ repos_to_enable }}"

    - name: Install EPEL repository
      shell: |
        dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ rhel_version }}.noarch.rpm
      args:
        creates: /etc/yum.repos.d/epel.repo

    - name: Clean and refresh metadata
      command: dnf makecache

    - name: Verify enabled repositories
      command: dnf repolist enabled
      register: repo_list
      changed_when: false

    - name: Show final repo list
      debug:
        msg: "{{ repo_list.stdout_lines }}"
