---
- name: Register system and add repositories
  hosts: vms
  gather_facts: yes

  vars:
    rhsm_username: "info@pacetechsystems.com"
    rhsm_password: "Silverado@8787!!!!"
    ansible_ssh_common_args: '-o AddressFamily=inet -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:
    - name: Display VM connection info
      debug:
        msg: "Connecting to VM at {{ ansible_host }}"

    - name: Register the system with Red Hat Subscription Manager
      shell: |
        subscription-manager register --username='{{ rhsm_username }}' --password='{{ rhsm_password }}' --auto-attach
      register: register_result

    - name: Install EPEL repository for RHEL 9
      shell: |
        dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      args:
        creates: /etc/yum.repos.d/epel.repo
