---
- name: Prepare VM network and enable RHEL repositories
  hosts: localhost
  gather_facts: false

  vars:
    vm_name: "apache-vm"
    vm_namespace: "vm-migration-test"
    vm_ip: "10.0.0.118"          # Use exported VM IP from create-VM playbook
    rhsm_username: "info@pacetechsystems.com"
    rhsm_password: "Silverado@8787!!!!"
    rhel_version: 9
    repos_to_enable:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - codeready-builder-for-rhel-9-x86_64-rpms
    google_dns:
      - "8.8.8.8"
      - "8.8.4.4"

  tasks:
    - name: Add VM to dynamic inventory
      add_host:
        name: "{{ vm_name }}"
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: password
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        groups: vms

    - name: Display added VM info
      debug:
        msg: "VM {{ vm_name }} ({{ vm_ip }}) added to dynamic group 'vms'"

- name: Configure network and register system on VM
  hosts: vms
  gather_facts: yes
  become: true

  vars:
    repos_to_enable:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - codeready-builder-for-rhel-9-x86_64-rpms
    registration_retries: 3
    registration_delay: 10

  tasks:

    # -----------------------------
    # Step 1: Configure network & DNS
    # -----------------------------
    - name: Ensure NetworkManager is installed
      package:
        name: NetworkManager
        state: present

    - name: Configure eth0 with DHCP and Google DNS
      nmcli:
        conn_name: eth0
        ifname: eth0
        type: ethernet
        state: up
        ipv4:
          method: auto
          dns: "{{ google_dns }}"
          ignore_auto_dns: yes
        ipv6:
          method: ignore

    - name: Restart NetworkManager to apply changes
      service:
        name: NetworkManager
        state: restarted

    - name: Verify connectivity
      shell: |
        ping -c 2 8.8.8.8 && ping -c 2 google.com
      register: ping_test
      failed_when: ping_test.rc != 0
      changed_when: false

    # -----------------------------
    # Step 2: Install subscription-manager
    # -----------------------------
    - name: Ensure subscription-manager is installed
      package:
        name: subscription-manager
        state: present

    - name: Unregister any existing registration
      shell: |
        subscription-manager remove --all || true
        subscription-manager unregister || true
        subscription-manager clean || true
      ignore_errors: true

    - name: Register the system with Red Hat Subscription Manager
      shell: |
        subscription-manager register \
          --username='{{ rhsm_username }}' \
          --password='{{ rhsm_password }}' \
          --auto-attach
      register: register_result
      retries: "{{ registration_retries }}"
      delay: "{{ registration_delay }}"
      until: register_result.rc == 0
      no_log: true

    - name: Wait for redhat.repo to appear
      wait_for:
        path: /etc/yum.repos.d/redhat.repo
        state: present
        timeout: 60

    # -----------------------------
    # Step 3: Enable RHEL repositories
    # -----------------------------
    - name: Disable all repos (clean start)
      shell: subscription-manager repos --disable="*"

    - name: Enable required RHEL repositories
      shell: "subscription-manager repos --enable={{ item }}"
      loop: "{{ repos_to_enable }}"

    - name: Install EPEL repository
      shell: |
        dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ rhel_version }}.noarch.rpm
      args:
        creates: /etc/yum.repos.d/epel.repo

    - name: Clean and refresh repo metadata
      shell: |
        dnf clean all
        dnf makecache

    - name: Verify repository access
      shell: dnf repolist enabled
      register: repolist
      changed_when: false

    - name: Display final enabled repositories
      debug:
        msg: "{{ repolist.stdout_lines }}"
