---
- name: Prepare VM inventory from wait-for-SSH fact
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: apache-vm
    vm_gateway: "10.0.0.1"
    vm_dns: "10.0.0.17,8.8.8.8"
    rhsm_username: "info@pacetechsystems.com"
    rhsm_password: "Silverado@8787!!!!"
    rhel_version: 9
    repos_to_enable:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - codeready-builder-for-rhel-9-x86_64-rpms
    registration_retries: 3
    registration_delay: 10
    cloud_init_password: "password"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  tasks:
    - name: Add apache-vm to in-memory inventory
      add_host:
        name: "{{ vm_name }}"
        ansible_host: "{{ vm_ip }}"   # <-- use the vm_ip fact from wait-for-SSH
        ansible_user: root
        ansible_password: "{{ cloud_init_password }}"
        ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"
        groups: dynamic_vms

    - name: Display VM IP
      debug:
        msg: "✅ Using VM IP from wait-for-SSH: {{ vm_ip }}"

- name: Configure network, register system, and enable RHEL repositories
  hosts: dynamic_vms
  gather_facts: false
  vars:
    vm_gateway: "10.0.0.1"
    vm_dns: "8.8.8.8"
    rhsm_username: "info@pacetechsystems.com"
    rhsm_password: "Silverado@8787!!!!"
    rhel_version: 9
    repos_to_enable:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - codeready-builder-for-rhel-9-x86_64-rpms
    registration_retries: 3
    registration_delay: 10

  tasks:
    - name: Ensure NetworkManager is installed
      package:
        name: NetworkManager
        state: present

    - name: Detect primary network interface
      command: nmcli -t -f DEVICE,STATE dev
      register: nmcli_devices

    - name: Set primary interface fact
      set_fact:
        primary_iface: "{{ nmcli_devices.stdout_lines | select('search', 'connected') | map('split', ':') | map('first') | list | first | default('eth0') }}"

    - name: Configure persistent static network for primary interface
      shell: |
        nmcli con delete "{{ primary_iface }}" || true
        nmcli con add type ethernet ifname "{{ primary_iface }}" con-name "{{ primary_iface }}" \
          ipv4.addresses {{ ansible_host }}/24 \
          ipv4.gateway {{ vm_gateway }} \
          ipv4.dns {{ vm_dns }} \
          ipv4.method manual autoconnect yes
        nmcli con up "{{ primary_iface }}"

    - name: Wait a few seconds for network to stabilize
      wait_for:
        timeout: 5

    - name: Test DNS resolution
      command: ping -c 2 google.com
      register: ping_result
      ignore_errors: true

    - name: Display DNS test result
      debug:
        var: ping_result

    - name: Ensure subscription-manager is installed
      package:
        name: subscription-manager
        state: present

    - name: Register system with RHSM (force if needed)
      shell: |
        subscription-manager register \
          --username='{{ rhsm_username }}' \
          --password='{{ rhsm_password }}' \
          --auto-attach \
          --force
      retries: "{{ registration_retries }}"
      delay: "{{ registration_delay }}"
      register: register_result
      until: register_result.rc == 0
      no_log: false

    - name: Disable all repos (clean start)
      command: subscription-manager repos --disable="*"

    - name: Enable required RHEL repositories
      shell: |
        for repo in {{ repos_to_enable | join(' ') }}; do
          if ! subscription-manager repos --list-enabled | grep -q "$repo"; then
            subscription-manager repos --enable="$repo"
          fi
        done

    - name: Import EPEL GPG key
      rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

    - name: Install EPEL repository if not present
      package:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ rhel_version }}.noarch.rpm"
        state: present

    - name: Clean and refresh metadata
      command: dnf makecache

    - name: Verify enabled repositories
      command: dnf repolist enabled
      register: repo_list
      changed_when: false

    - name: Show final repo list
      debug:
        msg: "{{ repo_list.stdout_lines }}"
