---
- hosts: localhost
  gather_facts: false

  vars:
    default_vm_name: "apache-vm"
    default_vm_namespace: "vm-migration-test"

  tasks:

    - name: Set effective VM name and namespace
      set_fact:
        vm_name: "{{ vm_name | default(default_vm_name) }}"
        vm_namespace: "{{ vm_namespace | default(default_vm_namespace) }}"

    - name: Get VMI information
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vmi_info
      ignore_errors: yes

    - name: Fail if VMI does not exist
      fail:
        msg: "❌ VMI '{{ vm_name }}' not found in namespace '{{ vm_namespace }}'."
      when: (vmi_info.resources | default([])) | length == 0

    - name: Fetch VM IPv4 from eth0
      set_fact:
        vm_ip: "{{ (vmi_info.resources[0].status.interfaces | selectattr('name','equalto','eth0') | list)[0].ipAddresses[0] }}"

    - name: Display VM IPv4
      debug:
        msg: "VM IPv4 to use for Service: {{ vm_ip }}"

    - name: Create Service with externalIPs
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP
            externalIPs:
              - "{{ vm_ip }}"

    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Wait for Route to be ready
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_info
      until: (route_info.resources | default([{}]))[0].spec.host is defined
      retries: 10
      delay: 2

    - name: Display deployment information
      debug:
        msg:
          - "==========================================================================="
          - "✅ Henogez WebServer Route Created Successfully!"
          - "==========================================================================="
          - "   Access your web server at:"
          - "   External URL (HTTPS): https://{{ route_info.resources[0].spec.host }}"
          - "   External URL (HTTP - will redirect): http://{{ route_info.resources[0].spec.host }}"
          - "   Internal Service: http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - "   Resource Details:"
          - "   VM Name: {{ vm_name }}"
          - "   Namespace: {{ vm_namespace }}"
          - "   Service: {{ vm_name }}-service"
          - "   Route: {{ vm_name }}-route"
          - "==========================================================================="
