---
- name: Create Service and Route for Apache VM using dynamic IPv4
  hosts: localhost
  gather_facts: false

  vars:
    default_vm_name: "apache-vm"
    default_vm_namespace: "vm-migration-test"

  tasks:

    - name: Set effective VM name and namespace
      set_fact:
        vm_name: "{{ vm_name | default(default_vm_name) }}"
        vm_namespace: "{{ vm_namespace | default(default_vm_namespace) }}"

    - name: Get VM IPv4 from dynamic inventory
      set_fact:
        vm_ip: "{{ hostvars['apache-vm'].ansible_default_ipv4.address | default('N/A') }}"
      when: "'apache-vm' in hostvars"

    - name: Fail if VM IP not found
      fail:
        msg: "❌ Could not fetch VM IP. Make sure the configure LAMP playbook ran successfully."
      when: vm_ip == 'N/A'

    - name: Display VM IPv4 for debugging
      debug:
        msg: "VM {{ vm_name }} IPv4: {{ vm_ip }}"

    - name: Create Service for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            selector:
              vm.kubevirt.io/name: "{{ vm_name }}"
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP

    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Wait for Route to be ready
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_info
      until: (route_info.resources | default([{}]))[0].spec.host is defined
      retries: 10
      delay: 5

    - name: Display Route information
      debug:
        msg:
          - "==========================================================================="
          - "✅ Henogez WebServer Route Created Successfully!"
          - "==========================================================================="
          - "   VM IPv4: {{ vm_ip }}"
          - "   External URL (HTTPS): https://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "   External URL (HTTP - will redirect): http://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "   Internal Service: http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - "   VM Name: {{ vm_name }}"
          - "   Namespace: {{ vm_namespace }}"
          - "   Service: {{ vm_name }}-service"
          - "   Route: {{ vm_name }}-route"
          - "==========================================================================="
