---
- name: Create VM on OpenShift Virtualization with IPv4 extraction (Multus + Masquerade)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # VM Configuration
    vm_name: apache-vm
    vm_project: vm-migration-test
    storage_class: nfs-storage-class
    storage_size: 15Gi
    memory_size: 2Gi
    cpu_cores: 2
    cpu_sockets: 1
    cpu_threads: 1

    # Authentication
    cloud_init_password: password

    # Network Configuration
    network_attachment: br-ex-network  # Multus network
    masquerade_network: default        # Masquerade (Pod network)

    # Timing Configuration
    ip_poll_interval: 10        # Seconds between IP checks
    max_ip_retries: 18          # Max retries (18 * 10 = 3 minutes)

  tasks:
    # ==========================================================================
    # STEP 1: DISPLAY CONFIGURATION
    # ==========================================================================
    - name: Display VM configuration
      debug:
        msg:
          - "=========================================="
          - "Creating VM: {{ vm_name }}"
          - "Namespace: {{ vm_project }}"
          - "Memory: {{ memory_size }}"
          - "CPU Cores: {{ cpu_cores }}"
          - "Storage Class: {{ storage_class }}"
          - "Network (Multus): {{ network_attachment }}"
          - "Network (Masquerade): {{ masquerade_network }}"
          - "=========================================="

    # ==========================================================================
    # STEP 2: CREATE VIRTUAL MACHINE
    # ==========================================================================
    - name: Provision Virtual Machine in OpenShift
      kubernetes.core.k8s:
        state: present
        validate_certs: no
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ vm_project }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            running: true
            dataVolumeTemplates:
              - metadata:
                  name: "{{ vm_name }}"
                  annotations:
                    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
                spec:
                  source:
                    pvc:
                      name: centos9-golden-image
                      namespace: "{{ vm_project }}"
                  storage:
                    storageClassName: "{{ storage_class }}"
                    accessModes: ["ReadWriteMany"]
                    volumeMode: Filesystem
                    resources:
                      requests:
                        storage: "{{ storage_size }}"
            template:
              metadata:
                labels:
                  kubevirt.io/domain: "{{ vm_name }}"
              spec:
                domain:
                  cpu:
                    cores: "{{ cpu_cores }}"
                    sockets: "{{ cpu_sockets }}"
                    threads: "{{ cpu_threads }}"
                  memory:
                    guest: "{{ memory_size }}"
                  devices:
                    disks:
                      - name: rootdisk
                        disk:
                          bus: virtio
                      - name: cloudinitdisk
                        disk:
                          bus: virtio
                    interfaces:
                      - name: br-ex-net
                        bridge: {}
                      - name: masq-net
                        masquerade: {}  # Masquerade interface
                networks:
                  - name: br-ex-net
                    multus:
                      networkName: "{{ vm_project }}/{{ network_attachment }}"
                  - name: masq-net
                    pod: {}   # Masquerade network
                volumes:
                  - name: rootdisk
                    dataVolume:
                      name: "{{ vm_name }}"
                  - name: cloudinitdisk
                    cloudInitNoCloud:
                      networkData: |
                        version: 2
                        ethernets:
                          eth0:
                            dhcp4: true   # Multus
                          eth1:
                            dhcp4: true   # Masquerade
                      userData: |
                        #cloud-config
                        user: root
                        password: {{ cloud_init_password }}
                        chpasswd: { expire: False }
                        ssh_pwauth: True
                        runcmd:
                          - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
                          - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
                          - systemctl restart sshd
                          - systemctl enable sshd
      register: vm_creation

    - name: Display VM creation result
      debug:
        msg: "VM {{ vm_name }} provisioned successfully"
      when: vm_creation.changed

    # ==========================================================================
    # STEP 3: WAIT FOR DATAVOLUME
    # ==========================================================================
    - name: Wait for DataVolume to be ready
      kubernetes.core.k8s_info:
        api_version: cdi.kubevirt.io/v1beta1
        kind: DataVolume
        name: "{{ vm_name }}"
        namespace: "{{ vm_project }}"
        validate_certs: no
      register: dv_info
      until:
        - dv_info.resources | length > 0
        - dv_info.resources[0].status.phase == "Succeeded"
      retries: 60
      delay: 10

    - name: Display DataVolume status
      debug:
        msg: "DataVolume ready (Phase: {{ dv_info.resources[0].status.phase }})"

    # ==========================================================================
    # STEP 4: WAIT FOR VM TO BE RUNNING
    # ==========================================================================
    - name: Wait for VM to be running
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_project }}"
        validate_certs: no
      register: vmi_info
      until:
        - vmi_info.resources | length > 0
        - vmi_info.resources[0].status.phase == "Running"
      retries: 30
      delay: 10

    - name: Display VM running status
      debug:
        msg: "VM {{ vm_name }} is running, waiting for IPv4 address..."

    # ==========================================================================
    # STEP 5: EXTRACT IPV4 (PREFER MASQUERADE)
    # ==========================================================================
    - name: Initialize IPv4 variables
      set_fact:
        vm_ipv4_addresses: []
        vm_ip: "No IPv4 assigned"
        all_ips: []

    - name: Extract IPv4 addresses from guest agent
      set_fact:
        all_ips: >-
          {{
            (vmi_info.resources[0].status.interfaces | default([])) |
            map(attribute='ipAddresses') |
            select('defined') |
            map('flatten') |
            flatten |
            list
          }}
        # Prefer Masquerade interface (eth1 / masq-net)
        vm_ipv4_addresses: >-
          {{
            (vmi_info.resources[0].status.interfaces | default([])) |
            selectattr('name','equalto','masq-net') |
            map(attribute='ipAddresses') |
            select('defined') |
            map('flatten') |
            flatten |
            select('match', '^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$') |
            list
          }}

    - name: Set final VM IP
      set_fact:
        vm_ip: "{{ vm_ipv4_addresses[0] if vm_ipv4_addresses | length > 0 else 'No IPv4 assigned' }}"

    - name: Display network information
      debug:
        msg:
          - "================================================"
          - "Network Information for {{ vm_name }}"
          - "================================================"
          - "All IPs detected: {{ all_ips | join(', ') if all_ips | length > 0 else 'None' }}"
          - "IPv4 addresses (Masquerade preferred): {{ vm_ipv4_addresses | join(', ') }}"
          - "Selected IPv4: {{ vm_ip }}"
          - "================================================"

    - name: Fail if no IPv4 address obtained
      fail:
        msg: "ERROR: No IPv4 address could be obtained for {{ vm_name }}!"
      when: vm_ip == 'No IPv4 assigned'

    # ==========================================================================
    # STEP 6: EXPORT VARIABLES
    # ==========================================================================
    - name: Export variables for workflow
      set_stats:
        data:
          vm_ip: "{{ vm_ip }}"
          vm_ipv4: "{{ vm_ipv4_addresses | join(',') }}"
          vm_name: "{{ vm_name }}"
          vm_project: "{{ vm_project }}"
        per_host: no
