---
- name: Create Route and Fetch VM Details
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: apache-vm
    vm_namespace: vm-migration-test
    service_name: apache-vm-service
    route_name: apache-vm-route
    retries: 10
    delay: 6
    kubeconfig_path: /etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/localhost.kubeconfig

  tasks:

    - name: Ensure KUBECONFIG is set
      ansible.builtin.set_env:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Get VM information
      community.kubernetes.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vm_info
      failed_when: vm_info.resources | length == 0

    - name: Get VMI information
      community.kubernetes.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vmi_info
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: vmi_info.resources | length > 0

    - name: Fetch VM IP (first IPv4)
      set_fact:
        vm_ip: "{{ (vmi_info.resources[0].status.interfaces | selectattr('ipAddresses','defined') | list)[0].ipAddresses[0] }}"
      when: vmi_info.resources | length > 0

    - name: Ensure Route exists
      community.kubernetes.k8s:
        api_version: route.openshift.io/v1
        kind: Route
        namespace: "{{ vm_namespace }}"
        name: "{{ route_name }}"
        state: present
        definition:
          spec:
            to:
              kind: Service
              name: "{{ service_name }}"
            port:
              targetPort: http
            tls:
              termination: edge
      register: route_result

    - name: Wait for route to be admitted
      command: >
        oc get route {{ route_name }} -n {{ vm_namespace }} -o jsonpath='{.status.ingress[0].conditions[?(@.type=="Admitted")].status}'
      register: route_status
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: route_status.stdout == "True"

    - name: Fetch Route hostname
      command: oc get route {{ route_name }} -n {{ vm_namespace }} -o jsonpath='{.spec.host}'
      register: route_hostname

    - name: Display VM and Route info
      debug:
        msg:
          - "External URL (HTTPS): https://{{ route_hostname.stdout }}"
          - "External URL (HTTP - will redirect): http://{{ route_hostname.stdout }}"
          - "-------------------------------------------------------------------"
          - "VM Name: {{ vm_name }}"
          - "Namespace: {{ vm_namespace }}"
          - "Service: {{ service_name }}"
          - "Route: {{ route_name }}"
          - "✅ Route Status: Admitted: True"
          - "Internal VM IP: http://{{ vm_ip }}"
          - "Internal Service: http://{{ service_name }}.{{ vm_namespace }}.svc.cluster.local"
          - "==================================================================="
