---
- name: Create VM on OpenShift Virtualization with IPv4 extraction (Multus + Masquerade)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # VM Configuration
    vm_name: apache-vm
    vm_project: vm-migration-test
    storage_class: nfs-storage-class
    storage_size: 15Gi
    memory_size: 2Gi
    cpu_cores: 2
    cpu_sockets: 1
    cpu_threads: 1

    # Authentication
    cloud_init_password: password

    # Network Configuration
    network_attachment: br-ex-network

    # Timing Configuration
    ip_poll_interval: 10        # Seconds between IP checks
    max_ip_retries: 18          # Max retries (18 * 10 = 3 minutes)

  tasks:
    - name: Display VM configuration
      debug:
        msg:
          - "=========================================="
          - "Creating VM: {{ vm_name }}"
          - "Namespace: {{ vm_project }}"
          - "Memory: {{ memory_size }}"
          - "CPU Cores: {{ cpu_cores }}"
          - "Storage Class: {{ storage_class }}"
          - "Network (Multus): {{ network_attachment }}"
          - "Network (Masquerade): enabled"
          - "=========================================="

    - name: Provision Virtual Machine in OpenShift
      kubernetes.core.k8s:
        state: present
        validate_certs: no
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ vm_project }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            running: true
            dataVolumeTemplates:
              - metadata:
                  name: "{{ vm_name }}"
                  annotations:
                    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
                spec:
                  source:
                    pvc:
                      name: centos9-golden-image
                      namespace: "{{ vm_project }}"
                  storage:
                    storageClassName: "{{ storage_class }}"
                    accessModes: ["ReadWriteMany"]
                    volumeMode: Filesystem
                    resources:
                      requests:
                        storage: "{{ storage_size }}"
            template:
              metadata:
                labels:
                  kubevirt.io/domain: "{{ vm_name }}"
              spec:
                domain:
                  cpu:
                    cores: "{{ cpu_cores }}"
                    sockets: "{{ cpu_sockets }}"
                    threads: "{{ cpu_threads }}"
                  memory:
                    guest: "{{ memory_size }}"
                  devices:
                    disks:
                      - name: rootdisk
                        disk:
                          bus: virtio
                      - name: cloudinitdisk
                        disk:
                          bus: virtio
                    interfaces:
                      - name: br-ex-net
                        bridge: {}                  # Multus interface
                      - name: masq-net
                        masquerade: {}              # Masquerade interface
                networks:
                  - name: br-ex-net
                    multus:
                      networkName: "{{ vm_project }}/{{ network_attachment }}"
                  - name: masq-net
                    pod: {}                       # Masquerade network
                volumes:
                  - name: rootdisk
                    dataVolume:
                      name: "{{ vm_name }}"
                  - name: cloudinitdisk
                    cloudInitNoCloud:
                      networkData: |
                        version: 2
                        ethernets:
                          eth0:
                            dhcp4: true
                          eth1:
                            dhcp4: true
                      userData: |
                        #cloud-config
                        user: root
                        password: {{ cloud_init_password }}
                        chpasswd: { expire: False }
                        ssh_pwauth: True
                        runcmd:
                          - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
                          - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
                          - systemctl restart sshd
                          - systemctl enable sshd
      register: vm_creation

    - name: Wait for VM to be running
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_project }}"
        validate_certs: no
      register: vmi_info
      until:
        - vmi_info.resources | length > 0
        - vmi_info.resources[0].status.phase == "Running"
      retries: 30
      delay: 10

    - name: Poll for Multus IPv4 address
      set_fact:
        vm_ipv4_multus: >-
          {{
            (vmi_info.resources[0].status.interfaces | default([])) |
            selectattr('name','equalto','br-ex-net') |
            map(attribute='ipAddresses') |
            select('defined') |
            map('flatten') |
            flatten |
            select('match', '^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$') |
            list
          }}
        vm_ip_multus: "{{ vm_ipv4_multus[0] | default('No IPv4 assigned') }}"

    - name: Display Multus network information
      debug:
        msg:
          - "=========================================="
          - "VM Name: {{ vm_name }}"
          - "Namespace: {{ vm_project }}"
          - "Multus IPv4: {{ vm_ip_multus }}"
          - "All Multus IPs: {{ vm_ipv4_multus | join(', ') }}"
          - "=========================================="

    - name: Fail if Multus IPv4 not obtained
      fail:
        msg: "ERROR: No Multus IPv4 address could be obtained for {{ vm_name }}!"
      when: vm_ip_multus == 'No IPv4 assigned'
