---
- name: Create Route for VM Service and Verify Access
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: apache-vm
    vm_namespace: vm-migration-test
    service_name: apache-vm-service
    route_name: apache-vm-route
    max_retries: 10
    retry_delay: 10

  tasks:
    - name: Set effective VM name and namespace
      set_fact:
        effective_vm_name: "{{ vm_name }}"
        effective_namespace: "{{ vm_namespace }}"

    - name: Get VM information
      command: >
        oc get vm {{ effective_vm_name }}
        -n {{ effective_namespace }}
        -o json
      register: vm_info
      failed_when: vm_info.rc != 0
      changed_when: false

    - name: Fetch VM IPv4
      set_fact:
        vm_ip: "{{ vm_info.stdout | from_json | json_query('status.interfaces[0].ipAddress') | default('') }}"
      when: vm_info.stdout | from_json | json_query('status.interfaces') is defined

    - name: Ensure VM IPv4 was found
      fail:
        msg: "Unable to determine IPv4 address for VM {{ effective_vm_name }}"
      when: vm_ip == ""

    - name: Ensure Service exists
      command: >
        oc get svc {{ service_name }} -n {{ effective_namespace }}
      register: svc_check
      failed_when: svc_check.rc != 0
      changed_when: false

    - name: Check if Route already exists
      command: >
        oc get route {{ route_name }} -n {{ effective_namespace }} -o jsonpath='{.spec.host}'
      register: route_host
      ignore_errors: true
      changed_when: false

    - name: Delete route if host is an internal IP
      command: oc delete route {{ route_name }} -n {{ effective_namespace }}
      when: route_host.stdout is match("^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$")
      ignore_errors: true

    - name: Recreate route with OpenShift auto-generated hostname if needed
      command: >
        oc expose svc/{{ service_name }}
        -n {{ effective_namespace }}
        --name={{ route_name }}
        --port=http
        --hostname=""
      when: route_host.stdout is match("^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$")
      register: recreate_route
      ignore_errors: true

    - name: Wait for route to be admitted
      retries: "{{ max_retries }}"
      delay: "{{ retry_delay }}"
      until: "'True' in route_status.stdout"
      vars:
        route_status: "{{ lookup('pipe', 'oc get route ' + route_name + ' -n ' + effective_namespace + ' -o jsonpath={.status.ingress[0].conditions[?(@.type==\"Admitted\")].status}') }}"
      ignore_errors: true

    - name: Get final route host
      command: >
        oc get route {{ route_name }} -n {{ effective_namespace }} -o jsonpath='{.spec.host}'
      register: final_route_host
      changed_when: false
      ignore_errors: true

    - name: Display summary
      debug:
        msg:
          - "==================================================================="
          - " ✅ VM and Route Configuration Summary"
          - "-------------------------------------------------------------------"
          - " VM Name: {{ effective_vm_name }}"
          - " Namespace: {{ effective_namespace }}"
          - " Service: {{ service_name }}"
          - " Route: {{ route_name }}"
          - " Route Host: {{ final_route_host.stdout | default('Unavailable') }}"
          - " Internal VM IP: http://{{ vm_ip }}"
          - " Internal Service: http://{{ service_name }}.{{ effective_namespace }}.svc.cluster.local"
          - "-------------------------------------------------------------------"
          - " Access via Route: http://{{ final_route_host.stdout | default('Unavailable') }}"
          - "==================================================================="
