---
- name: Create OpenShift Service and Route for VM
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # These variables come from previous jobs
    vm_name: "{{ vm_name | default('apache-vm') }}"
    vm_project: "{{ vm_project | default('vm-migration-test') }}"
    vm_ip: "{{ vm_ip | default('') }}"
    
    # Service and Route names
    service_name: "{{ vm_name }}-service"
    route_name: "{{ vm_name }}-route"
    
    # Service configuration
    service_port: 80
    target_port: 80

  tasks:
    # ==========================================================================
    # STEP 1: DISPLAY CONFIGURATION
    # ==========================================================================
    - name: Display configuration
      debug:
        msg:
          - "=========================================="
          - "Creating Service and Route"
          - "=========================================="
          - "VM Name: {{ vm_name }}"
          - "VM IP: {{ vm_ip }}"
          - "Namespace: {{ vm_project }}"
          - "Service: {{ service_name }}"
          - "Route: {{ route_name }}"
          - "=========================================="

    - name: Validate VM IP
      fail:
        msg: "ERROR: VM IP is required to create service. vm_ip = {{ vm_ip }}"
      when: vm_ip == '' or vm_ip is not defined

    # ==========================================================================
    # STEP 2: CREATE SERVICE
    # ==========================================================================
    - name: Create Service for VM
      kubernetes.core.k8s:
        state: present
        validate_certs: no
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ service_name }}"
            namespace: "{{ vm_project }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            type: ClusterIP
            ports:
              - name: http
                port: "{{ service_port }}"
                targetPort: "{{ target_port }}"
                protocol: TCP
            selector:
              kubevirt.io/domain: "{{ vm_name }}"
      register: service_result

    - name: Display service creation result
      debug:
        msg: "Service {{ service_name }} {{ 'created' if service_result.changed else 'already exists' }}"

    # ==========================================================================
    # STEP 3: CREATE ROUTE
    # ==========================================================================
    - name: Create Route for Service
      kubernetes.core.k8s:
        state: present
        validate_certs: no
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ route_name }}"
            namespace: "{{ vm_project }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            to:
              kind: Service
              name: "{{ service_name }}"
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
      register: route_result

    - name: Display route creation result
      debug:
        msg: "Route {{ route_name }} {{ 'created' if route_result.changed else 'already exists' }}"

    # ==========================================================================
    # STEP 4: GET ROUTE DETAILS
    # ==========================================================================
    - name: Wait for route to be ready
      pause:
        seconds: 5

    - name: Get Route information
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ route_name }}"
        namespace: "{{ vm_project }}"
        validate_certs: no
      register: route_info

    - name: Extract route URL
      set_fact:
        route_host: "{{ route_info.resources[0].spec.host | default('Not assigned yet') }}"
        route_url: "https://{{ route_info.resources[0].spec.host }}"
        route_status: "{{ route_info.resources[0].status.ingress[0].conditions | selectattr('type', 'equalto', 'Admitted') | map(attribute='status') | first | default('Unknown') }}"
      when: 
        - route_info.resources is defined
        - route_info.resources | length > 0

    # ==========================================================================
    # STEP 5: GET SERVICE DETAILS
    # ==========================================================================
    - name: Get Service information
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        name: "{{ service_name }}"
        namespace: "{{ vm_project }}"
        validate_certs: no
      register: service_info

    - name: Extract service details
      set_fact:
        service_cluster_ip: "{{ service_info.resources[0].spec.clusterIP | default('N/A') }}"
        service_ports: "{{ service_info.resources[0].spec.ports | map(attribute='port') | list | join(', ') }}"
      when:
        - service_info.resources is defined
        - service_info.resources | length > 0

    # ==========================================================================
    # STEP 6: EXPORT VARIABLES
    # ==========================================================================
    - name: Export route URL for downstream jobs
      set_stats:
        data:
          route_url: "{{ route_url }}"
          route_host: "{{ route_host }}"
          service_name: "{{ service_name }}"
          route_name: "{{ route_name }}"
        per_host: no

    # ==========================================================================
    # STEP 7: DISPLAY SUMMARY
    # ==========================================================================
    - name: Display complete summary
      debug:
        msg:
          - "=========================================="
          - "Service and Route Created Successfully!"
          - "=========================================="
          - ""
          - "VM Details:"
          - "  VM Name: {{ vm_name }}"
          - "  VM IP: {{ vm_ip }}"
          - "  Namespace: {{ vm_project }}"
          - ""
          - "Service Details:"
          - "  Service Name: {{ service_name }}"
          - "  Cluster IP: {{ service_cluster_ip }}"
          - "  Ports: {{ service_ports }}"
          - ""
          - "Route Details:"
          - "  Route Name: {{ route_name }}"
          - "  Route Status: {{ route_status }}"
          - "  Route Host: {{ route_host }}"
          - ""
          - "=========================================="
          - "ACCESS YOUR APPLICATION:"
          - "=========================================="
          - ""
          - "  URL: {{ route_url }}"
          - ""
          - "  Click or copy the URL above to access your VM service"
          - ""
          - "=========================================="
          - ""
          - "Verification Commands:"
          - "  oc get route {{ route_name }} -n {{ vm_project }}"
          - "  oc get service {{ service_name }} -n {{ vm_project }}"
          - "  curl {{ route_url }}"
          - ""
          - "Exported Variables:"
          - "  route_url: {{ route_url }}"
          - "  route_host: {{ route_host }}"
          - "=========================================="
