---
- hosts: localhost
  gather_facts: false
  environment:
    KUBECONFIG: /etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/localhost.kubeconfig

  vars:
    default_vm_name: "apache-vm"
    default_vm_namespace: "vm-migration-test"
    retries: 5
    delay: 5

  tasks:

    - name: Set effective VM name and namespace
      set_fact:
        vm_name: "{{ vm_name | default(default_vm_name) }}"
        vm_namespace: "{{ vm_namespace | default(default_vm_namespace) }}"

    - name: Get VM information
      command: "oc get vmi {{ vm_name }} -n {{ vm_namespace }} -o json"
      register: vm_info
      failed_when: vm_info.rc != 0

    - name: Fail if VM does not exist
      fail:
        msg: "❌ VM '{{ vm_name }}' not found in namespace '{{ vm_namespace }}'."
      when: vm_info.stdout | from_json | length == 0

    - name: Fetch VM IPv4 from first interface with IPv4
      set_fact:
        vm_ip: "{{ (vm_info.stdout | from_json).status.interfaces | selectattr('ip', 'defined') | map(attribute='ip') | select('match','^\\d+\\.\\d+\\.\\d+\\.\\d+$') | first }}"
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: vm_ip is defined

    - name: Debug VM IP
      debug:
        msg: "✅ VM IPv4 detected: {{ vm_ip }}"

    - name: Create Service for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            selector:
              vm.kubevirt.io/name: "{{ vm_name }}"
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP

    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Wait for Route to be admitted
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_info
      retries: 10
      delay: 5
      until: route_info.resources[0].status.ingress is defined and route_info.resources[0].status.ingress[0].conditions[0].status == "True"

    - name: Display deployment information
      debug:
        msg:
          - "==========================================================================="
          - "✅ Henogez WebServer Route Created Successfully!"
          - "==========================================================================="
          - "   Internal VM IP: http://{{ vm_ip }}"
          - "   Internal Service: http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - "   External URL (HTTPS): https://{{ route_info.resources[0].spec.host }}"
          - "   External URL (HTTP - will redirect): http://{{ route_info.resources[0].spec.host }}"
          - "   Resource Details:"
          - "   VM Name: {{ vm_name }}"
          - "   Namespace: {{ vm_namespace }}"
          - "   Service: {{ vm_name }}-service"
          - "   Route: {{ vm_name }}-route"
          - "   Route Status: Admitted: {{ route_info.resources[0].status.ingress[0].conditions[0].status }}"
          - "==========================================================================="
