---
- hosts: localhost
  gather_facts: false
  vars:
    vm_name: apache-vm
    vm_namespace: vm-migration-test
    service_name: "{{ vm_name }}-service"
    route_name: "{{ vm_name }}-route"
    retries: 10
    delay: 5

  tasks:
    - name: Export KUBECONFIG for this session
      shell: export KUBECONFIG=/etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/localhost.kubeconfig
      register: kubeconfig_set

    - name: Ensure Service exists for VM
      shell: |
        export KUBECONFIG=/etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/localhost.kubeconfig
        oc apply -f - 
      args:
        stdin: |
          apiVersion: v1
          kind: Service
          metadata:
            name: {{ service_name }}
            namespace: {{ vm_namespace }}
            labels:
              app: {{ vm_name }}
          spec:
            selector:
              vm.kubevirt.io/name: {{ vm_name }}
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP

    - name: Ensure Route exists for VM
      shell: |
        export KUBECONFIG=/etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/localhost.kubeconfig
        oc apply -f - 
      args:
        stdin: |
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: {{ route_name }}
            namespace: {{ vm_namespace }}
            labels:
              app: {{ vm_name }}
          spec:
            to:
              kind: Service
              name: {{ service_name }}
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Get external route host
      shell: |
        export KUBECONFIG=/etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/localhost.kubeconfig
        oc get route {{ route_name }} -n {{ vm_namespace }} -o jsonpath='{.spec.host}'
      register: external_route
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: external_route.stdout != ""

    - name: Display internal and external URLs
      debug:
        msg:
          - "Internal Service URL: http://{{ service_name }}.{{ vm_namespace }}.svc.cluster.local"
          - "External Route URL: https://{{ external_route.stdout }}"
