---
- hosts: localhost
  gather_facts: false
  vars:
    default_vm_name: "apache-vm"
    default_vm_namespace: "vm-migration-test"
    retries: 10
    delay: 5

  tasks:
    - name: Set effective VM name and namespace
      set_fact:
        vm_name: "{{ vm_name | default(default_vm_name) }}"
        vm_namespace: "{{ vm_namespace | default(default_vm_namespace) }}"

    - name: Ensure KUBECONFIG is set
      ansible.builtin.shell: |
        export KUBECONFIG=/etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/localhost.kubeconfig
      args:
        executable: /bin/bash

    - name: Get VM information
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vm_info
      failed_when: vm_info.resources | length == 0

    - name: Get VMI information
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vmi_info
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: vmi_info.resources | length > 0 and vmi_info.resources[0].status.phase == "Running"

    - name: Fetch first IPv4 address from VM interfaces
      set_fact:
        vm_ip: "{{ (vmi_info.resources[0].status.interfaces | selectattr('ipAddress','defined') | list)[0].ipAddress }}"
      when: vmi_info.resources[0].status.interfaces is defined
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: vm_ip is defined

    - name: Create Service for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            selector:
              vm.kubevirt.io/name: "{{ vm_name }}"
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP

    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Wait for Route to have a host assigned
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_info
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: route_info.resources | length > 0 and route_info.resources[0].spec.host is defined

    - name: Verify Service endpoint is ready
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Endpoints
        name: "{{ vm_name }}-service"
        namespace: "{{ vm_namespace }}"
      register: service_endpoints
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: service_endpoints.resources[0].subsets is defined and service_endpoints.resources[0].subsets | length > 0

    - name: Display deployment information
      debug:
        msg:
          - "==========================================================================="
          - "✅ Henogez WebServer Deployment Details"
          - "==========================================================================="
          - "Internal VM IP: http://{{ vm_ip | default('N/A') }}"
          - "Internal Service: http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - "External URL (HTTPS): https://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "External URL (HTTP - will redirect): http://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "-------------------------------------------------------------------"
          - "VM Name: {{ vm_name }}"
          - "Namespace: {{ vm_namespace }}"
          - "Service: {{ vm_name }}-service"
          - "Route: {{ vm_name }}-route"
          - "✅ Route Status: Admitted: {{ (route_info.resources | default([{}]))[0].status.ingress[0].conditions[0].status | default('Unknown') }}"
          - "==========================================================================="
