---
- name: Create OpenShift Route for VM and Verify Application
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: apache-vm
    vm_namespace: vm-migration-test
    route_name: apache-vm-route
    service_name: apache-vm-service
    max_retries: 10
    retry_delay: 10

  tasks:
    - name: Set effective VM name and namespace
      set_fact:
        effective_vm_name: "{{ vm_name }}"
        effective_namespace: "{{ vm_namespace }}"

    - name: Get VM information
      command: oc get vm {{ effective_vm_name }} -n {{ effective_namespace }} -o json
      register: vm_info
      changed_when: false
      failed_when: vm_info.rc != 0

    - name: Fail if VM does not exist
      fail:
        msg: "VM {{ effective_vm_name }} not found in namespace {{ effective_namespace }}"
      when: vm_info.rc != 0

    - name: Fetch VM IPv4 from VMI status
      command: oc get vmi {{ effective_vm_name }} -n {{ effective_namespace }} -o json
      register: vmi_info
      changed_when: false
      retries: 10
      delay: 10
      until: vmi_info.stdout | from_json | json_query('status.interfaces[0].ipAddress') is defined

    - name: Set VM IPv4 fact
      set_fact:
        vm_ipv4: "{{ (vmi_info.stdout | from_json).status.interfaces[0].ipAddress }}"

    - name: Ensure Service exists for VM
      shell: |
        oc get svc {{ service_name }} -n {{ effective_namespace }} >/dev/null 2>&1 || \
        oc expose virtualmachineinstance {{ effective_vm_name }} -n {{ effective_namespace }} --name {{ service_name }} --port=80
      register: svc_output
      changed_when: "'created' in svc_output.stdout"

    - name: Ensure Route exists for VM
      shell: |
        oc get route {{ route_name }} -n {{ effective_namespace }} >/dev/null 2>&1 || \
        oc create route edge {{ route_name }} --service={{ service_name }} --insecure-policy=Redirect --port=http
      register: route_output
      changed_when: "'created' in route_output.stdout"

    # ✅ FIXED SECTION BELOW
    - name: Wait for route to be admitted
      vars:
        route_check_cmd: >
          oc get route {{ route_name }} -n {{ effective_namespace }}
          -o jsonpath='{.status.ingress[0].conditions[?(@.type=="Admitted")].status}'
      register: route_status
      until: route_status.stdout is search("True")
      retries: "{{ max_retries }}"
      delay: "{{ retry_delay }}"
      ignore_errors: true
      changed_when: false
      command: "{{ route_check_cmd }}"

    - name: Get route host
      command: oc get route {{ route_name }} -n {{ effective_namespace }} -o jsonpath='{.spec.host}'
      register: route_host
      changed_when: false

    - name: Display resource summary
      debug:
        msg:
          - "==================================================================="
          - " 🌐 Access Information"
          - "-------------------------------------------------------------------"
          - " Internal VM IP: http://{{ vm_ipv4 }}"
          - " Internal Service: http://{{ service_name }}.{{ effective_namespace }}.svc.cluster.local"
          - " External Route: https://{{ route_host.stdout }}"
          - "-------------------------------------------------------------------"
          - " Resource Details:"
          - " VM Name: {{ effective_vm_name }}"
          - " Namespace: {{ effective_namespace }}"
          - " Service: {{ service_name }}"
          - " Route: {{ route_name }}"
          - " ------------------------------------------------------------------"
          - " ✅ Route Status: Admitted: {{ 'True' if 'True' in route_status.stdout else 'False' }}"
          - "==================================================================="
