---
- hosts: localhost
  gather_facts: false

  vars:
    default_vm_name: "apache-vm"
    default_vm_namespace: "vm-migration-test"
    # Retry/delay settings
    retries: 10
    delay: 5

  tasks:
    - name: Ensure KUBECONFIG is set
      ansible.builtin.set_env:
        KUBECONFIG: "/home/hogege/kubeconfig"

    - name: Set effective VM name and namespace
      set_fact:
        vm_name: "{{ vm_name | default(default_vm_name) }}"
        vm_namespace: "{{ vm_namespace | default(default_vm_namespace) }}"

    - name: Get VM information
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vm_info
      ignore_errors: yes

    - name: Fail if VM does not exist
      fail:
        msg: "❌ VM '{{ vm_name }}' not found in namespace '{{ vm_namespace }}'."
      when: (vm_info.resources | default([])) | length == 0

    - name: Get VMI information
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vmi_info

    - name: Fetch first IPv4 address from VM interfaces safely
      set_fact:
        vm_ip: >-
          {{
            (vmi_info.resources[0].status.interfaces
            | selectattr('ipAddresses', 'defined')
            | selectattr('ipAddresses', 'length')
            | list
            | first).ipAddresses[0]
            if (vmi_info.resources[0].status.interfaces | length > 0)
            else 'N/A'
          }}

    - name: Create Service for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            selector:
              vm.kubevirt.io/name: "{{ vm_name }}"
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP

    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Wait for Route to be ready
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_info
      until: (route_info.resources | default([{}]))[0].spec.host is defined
      retries: "{{ retries }}"
      delay: "{{ delay }}"

    - name: Get Route status details
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_status

    - name: Display deployment information
      debug:
        msg:
          - "==========================================================================="
          - "✅ Henogez WebServer Route Created Successfully!"
          - "==========================================================================="
          - "   External URL (HTTPS): https://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "   External URL (HTTP - will redirect): http://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "   Internal VM IP: http://{{ vm_ip }}"
          - "   Internal Service: http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - "-------------------------------------------------------------------"
          - "   VM Name: {{ vm_name }}"
          - "   Namespace: {{ vm_namespace }}"
          - "   Service: {{ vm_name }}-service"
          - "   Route: {{ vm_name }}-route"
          - "   ✅ Route Status: Admitted: {{ (route_status.resources | default([{}]))[0].status.ingress[0].conditions[0].status | default('Unknown') }}"
          - "==========================================================================="
