---
- name: Create OpenShift Service and Route for Apache VM
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    vm_name: apache-vm
    vm_namespace: vm-migration-test
    svc_port: 80
    target_port: 80

  tasks:
    - name: Ensure oc CLI is available
      command: which oc
      register: oc_check
      failed_when: oc_check.rc != 0
      changed_when: false

    - name: Ensure KUBECONFIG is set
      environment:
        KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) }}"
      ansible.builtin.command: oc whoami
      register: whoami_result
      changed_when: false

    - name: Display OpenShift user
      debug:
        msg: "Logged in as: {{ whoami_result.stdout }}"

    - name: Ensure target namespace exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ vm_namespace }}"

    - name: Create Service for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            selector:
              app: "{{ vm_name }}"
            ports:
              - protocol: TCP
                port: "{{ svc_port }}"
                targetPort: "{{ target_port }}"
                name: http

    - name: Get OpenShift router domain
      command: oc get ingresscontroller default -n openshift-ingress-operator -o jsonpath='{.status.domain}'
      register: ingress_domain
      changed_when: false

    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            host: "{{ vm_name }}-{{ vm_namespace }}.{{ ingress_domain.stdout }}"
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Retrieve Route details
      command: oc get route {{ vm_name }}-route -n {{ vm_namespace }} -o jsonpath='{.spec.host}'
      register: route_host
      changed_when: false

    - name: Display Route information
      debug:
        msg:
          - "🌐 Application Route Created Successfully!"
          - ""
          - "🔹 Namespace: {{ vm_namespace }}"
          - "🔹 Service: {{ vm_name }}-service"
          - "🔹 Route: {{ vm_name }}-route"
          - ""
          - "✅ External HTTPS URL:"
          - "https://{{ route_host.stdout }}"
          - ""
          - "To test it:"
          - "curl -k https://{{ route_host.stdout }}"
