---
- name: Create Route and Fetch VM Details
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: apache-vm
    vm_namespace: vm-migration-test
    retries: 10
    delay: 10

  tasks:

    - name: Ensure KUBECONFIG is set
      ansible.builtin.set_fact:
        ansible_env:
          KUBECONFIG: /home/hogege/kubeconfig  # <-- Update path as needed

    - name: Fail if VM does not exist
      ansible.builtin.command: >
        oc get vm {{ vm_name }} -n {{ vm_namespace }}
      register: vm_check
      failed_when: vm_check.rc != 0
      changed_when: false

    - name: Get VMI IP via oc
      ansible.builtin.command: >
        oc get vmi {{ vm_name }} -n {{ vm_namespace }} -o jsonpath='{.status.interfaces[0].ip}'
      register: vm_ip
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: vm_ip.stdout != ""
      changed_when: false

    - name: Get OpenShift cluster domain via oc
      ansible.builtin.command: >
        oc get ingresses.config/cluster -o jsonpath='{.spec.domain}'
      register: cluster_domain
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: cluster_domain.stdout != ""
      changed_when: false

    - name: Get route hostname
      ansible.builtin.command: >
        oc get route {{ vm_name }}-route -n {{ vm_namespace }} -o jsonpath='{.spec.host}'
      register: route_host
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: route_host.stdout != ""
      changed_when: false

    - name: Display VM and Route Details
      ansible.builtin.debug:
        msg:
          - "External URL (HTTPS): https://{{ route_host.stdout }}"
          - "External URL (HTTP - will redirect): http://{{ route_host.stdout }}"
          - "Internal VM IP: http://{{ vm_ip.stdout }}"
          - "Internal Service: http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - "Resource Details:"
          - "  VM Name: {{ vm_name }}"
          - "  Namespace: {{ vm_namespace }}"
          - "  Service: {{ vm_name }}-service"
          - "  Route: {{ vm_name }}-route"
