---
- hosts: localhost
  gather_facts: false

  vars:
    default_vm_name: "apache-vm"
    default_vm_namespace: "vm-migration-test"
    apps_domain: "apps.ocp4.henogez.com"  # Set your OpenShift apps domain here
    retries: 10
    delay: 3

  tasks:

    - name: Set effective VM name and namespace
      set_fact:
        vm_name: "{{ vm_name | default(default_vm_name) }}"
        vm_namespace: "{{ vm_namespace | default(default_vm_namespace) }}"

    - name: Export KUBECONFIG for OpenShift CLI access
      ansible.builtin.shell: export KUBECONFIG=/etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/localhost.kubeconfig
      args:
        executable: /bin/bash

    - name: Get VM information
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vmi_info
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: vmi_info.resources | length > 0

    - name: Fail if VM does not exist
      fail:
        msg: "❌ VM '{{ vm_name }}' not found in namespace '{{ vm_namespace }}'."
      when: (vmi_info.resources | default([])) | length == 0

    - name: Fetch first IPv4 address from VM interfaces
      set_fact:
        vm_ip: >-
          {{
            (vmi_info.resources[0].status.interfaces | selectattr('ipAddresses','defined') |
            map(attribute='ipAddresses') | list | flatten | select('match', '^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$') |
            list)[0]
          }}
      when: vmi_info.resources[0].status.interfaces is defined

    - name: Create ClusterIP Service for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            selector:
              vm.kubevirt.io/name: "{{ vm_name }}"
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP

    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            host: "{{ vm_name }}-route-{{ vm_namespace }}.{{ apps_domain }}"
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Wait for Route to be admitted
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_info
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: (route_info.resources | default([{}]))[0].status.ingress[0].conditions[0].status == "True"

    - name: Display deployment information
      debug:
        msg:
          - "==========================================================================="
          - "✅ Henogez WebServer Route Created Successfully!"
          - "==========================================================================="
          - "   Access your web server at:"
          - "   External URL (HTTPS): https://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "   External URL (HTTP - will redirect): http://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "   Internal VM IP: http://{{ vm_ip | default('N/A') }}"
          - "   Internal Service: http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - "   Resource Details:"
          - "   VM Name: {{ vm_name }}"
          - "   Namespace: {{ vm_namespace }}"
          - "   Service: {{ vm_name }}-service"
          - "   Route: {{ vm_name }}-route"
          - "   ✅ Route Status: Admitted: {{ (route_info.resources | default([{}]))[0].status.ingress[0].conditions[0].status | default('Unknown') }}"
          - "==========================================================================="
