---
- name: Create VM on OpenShift Virtualization with IPv4 extraction
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # VM Configuration
    vm_name: apache-vm
    vm_project: vm-migration-test
    storage_class: nfs-storage-class
    storage_size: 15Gi
    memory_size: 2Gi
    cpu_cores: 2
    cpu_sockets: 1
    cpu_threads: 1

    # Authentication
    cloud_init_password: password

    # Network Configuration
    network_type: masquerade

    # Timing Configuration
    ip_poll_interval: 10
    max_ip_retries: 18

  tasks:
    - name: Display VM configuration
      debug:
        msg:
          - "=========================================="
          - "Creating VM: {{ vm_name }}"
          - "Namespace: {{ vm_project }}"
          - "Memory: {{ memory_size }}"
          - "CPU Cores: {{ cpu_cores }}"
          - "Storage Class: {{ storage_class }}"
          - "Network: {{ network_type }}"
          - "=========================================="

    - name: Provision Virtual Machine in OpenShift
      kubernetes.core.k8s:
        state: present
        validate_certs: no
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ vm_project }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            running: true
            dataVolumeTemplates:
              - metadata:
                  name: "{{ vm_name }}"
                  annotations:
                    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
                spec:
                  source:
                    pvc:
                      name: centos9-golden-image
                      namespace: "{{ vm_project }}"
                  storage:
                    storageClassName: "{{ storage_class }}"
                    accessModes: ["ReadWriteMany"]
                    volumeMode: Filesystem
                    resources:
                      requests:
                        storage: "{{ storage_size }}"
            template:
              metadata:
                labels:
                  kubevirt.io/domain: "{{ vm_name }}"
              spec:
                domain:
                  cpu:
                    cores: "{{ cpu_cores }}"
                    sockets: "{{ cpu_sockets }}"
                    threads: "{{ cpu_threads }}"
                  memory:
                    guest: "{{ memory_size }}"
                  devices:
                    disks:
                      - name: rootdisk
                        disk:
                          bus: virtio
                      - name: cloudinitdisk
                        disk:
                          bus: virtio
                    interfaces:
                      - name: default
                        masquerade: {}
                networks:
                  - name: default
                    pod: {}
                volumes:
                  - name: rootdisk
                    dataVolume:
                      name: "{{ vm_name }}"
                  - name: cloudinitdisk
                    cloudInitNoCloud:
                      networkData: |
                        version: 2
                        ethernets:
                          eth0:
                            dhcp4: true
                      userData: |
                        #cloud-config
                        user: root
                        password: {{ cloud_init_password }}
                        chpasswd: { expire: False }
                        ssh_pwauth: True
                        runcmd:
                          - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
                          - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
                          - systemctl restart sshd
                          - systemctl enable sshd
      register: vm_creation

    - name: Display VM creation result
      debug:
        msg: "VM {{ vm_name }} provisioned successfully"
      when: vm_creation.changed

    # ==========================================================================
    # Wait for DataVolume
    # ==========================================================================
    - name: Wait for DataVolume to be ready
      kubernetes.core.k8s_info:
        api_version: cdi.kubevirt.io/v1beta1
        kind: DataVolume
        name: "{{ vm_name }}"
        namespace: "{{ vm_project }}"
        validate_certs: no
      register: dv_info
      until:
        - dv_info.resources | length > 0
        - dv_info.resources[0].status.phase == "Succeeded"
      retries: 60
      delay: 10

    - name: Display DataVolume status
      debug:
        msg: "DataVolume ready (Phase: {{ dv_info.resources[0].status.phase }})"

    # ==========================================================================
    # Wait for VM to be running
    # ==========================================================================
    - name: Wait for VM to be running
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_project }}"
        validate_certs: no
      register: vmi_info
      until:
        - vmi_info.resources | length > 0
        - vmi_info.resources[0].status.phase == "Running"
      retries: 30
      delay: 10

    - name: Display VM running status
      debug:
        msg: "VM {{ vm_name }} is running, waiting for IPv4 address..."

    # ==========================================================================
    # Initialize IPv4 variables
    # ==========================================================================
    - name: Initialize variables
      set_fact:
        vm_ipv4_addresses: []
        vm_ip: ""

    # ==========================================================================
    # Poll for IPv4 via guest agent
    # ==========================================================================
    - name: Poll for IPv4 via guest agent
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_project }}"
        validate_certs: no
      register: vmi_network_info
      until: >
        (vmi_network_info.resources | length > 0) and
        ((vmi_network_info.resources[0].status.interfaces | default([]) |
          map(attribute='ipAddresses') | select('defined') | map('flatten') | flatten |
          select('match', '^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$') | list) | length > 0)
      retries: 30
      delay: 10

    - name: Extract IPv4 from guest agent
      set_fact:
        vm_ipv4_addresses: >-
          {{
            (vmi_network_info.resources[0].status.interfaces | default([])) |
            map(attribute='ipAddresses') |
            select('defined') |
            map('flatten') |
            flatten |
            select('match', '^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$') |
            list
          }}
        vm_ip: "{{ vm_ipv4_addresses[0] if vm_ipv4_addresses | length > 0 else '' }}"

    # ==========================================================================
    # SSH fallback using vm_ip
    # ==========================================================================
    - name: Wait for SSH to be available
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        timeout: 120
        delay: 10
      when: vm_ip != ''
      register: ssh_available
      ignore_errors: true

    - name: SSH fallback to extract IPv4 (if guest agent failed)
      shell: |
        sshpass -p '{{ cloud_init_password }}' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10 root@{{ vm_ip }} "ip -4 addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1"
      register: ssh_ipv4
      when:
        - vm_ip != ''
        - ssh_available is succeeded
      ignore_errors: true
      changed_when: false

    - name: Update vm_ip from SSH fallback if needed
      set_fact:
        vm_ip: "{{ ssh_ipv4.stdout | trim }}"
      when:
        - ssh_ipv4 is defined
        - ssh_ipv4.rc == 0
        - ssh_ipv4.stdout | trim != ''

    - name: Display final VM IP
      debug:
        msg: "VM IP Address: {{ vm_ip }}"

    - name: Fail if no IPv4 address obtained
      fail:
        msg: "ERROR: No IPv4 address could be obtained for VM {{ vm_name }}"
      when: vm_ip == ''

    # ==========================================================================
    # Export variables
    # ==========================================================================
    - name: Export variables
      set_stats:
        data:
          vm_ip: "{{ vm_ip }}"
          vm_name: "{{ vm_name }}"
          vm_project: "{{ vm_project }}"
        per_host: no
