---
- hosts: localhost
  gather_facts: no
  vars:
    vm_name: "{{ vm_name | default('apache-vm') }}"
    vm_namespace: "{{ vm_namespace | default('vm-migration-test') }}"

  tasks:
    - name: Get VM information
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vm_info
      ignore_errors: yes

    - name: Display VM labels for debugging
      debug:
        msg: "VM Labels: {{ vm_info.resources[0].metadata.labels | default({}) }}"
      when: vm_info.resources | length > 0

    - name: Fail if VM does not exist
      fail:
        msg: "❌ VM '{{ vm_name }}' not found in namespace '{{ vm_namespace }}'. Check creation step."
      when: vm_info.resources | length == 0

    - name: Create Service for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            selector:
              vm.kubevirt.io/name: "{{ vm_name }}"
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP

    - name: Verify Service endpoints
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Endpoints
        name: "{{ vm_name }}-service"
        namespace: "{{ vm_namespace }}"
      register: service_endpoints

    - name: Display Service endpoint status
      debug:
        msg: "Service Endpoints: {{ service_endpoints.resources[0].subsets | default([]) }}"
      when:
        - service_endpoints.resources | length > 0
        - service_endpoints.resources[0].subsets is defined
        - service_endpoints.resources[0].subsets | length > 0

    - name: Display warning if no endpoints found
      debug:
        msg: "⚠ Warning: No endpoints found! Check if VM selector matches."
      when:
        - service_endpoints.resources | length == 0 or
          service_endpoints.resources[0].subsets is not defined or
          service_endpoints.resources[0].subsets | length == 0

    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Wait for Route to have a host
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_info
      until: route_info.resources[0].spec.host is defined and route_info.resources[0].spec.host | default('') != ''
      retries: 10
      delay: 3

    - name: Get Route status details
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_status

    - name: Display deployment information
      debug:
        msg:
          - "=================================================================="
          - "Henogez WebServer Route Created Successfully!"
          - "=================================================================="
          - "   Access your web server at:"
          - "   External URL (HTTPS): https://{{ route_info.resources[0].spec.host | default('Not ready') }}"
          - "   External URL (HTTP - will redirect): http://{{ route_info.resources[0].spec.host | default('Not ready') }}"
          - "   Internal Service: http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - "   Resource Details:"
          - "   VM Name: {{ vm_name }}"
          - "   Namespace: {{ vm_namespace }}"
          - "   Service: {{ vm_name }}-service"
          - "   Route: {{ vm_name }}-route"
          - "   Route Status: {{ route_status.resources[0].status.ingress[0].conditions[0].status | default('Unknown') }}"
          - "=================================================================="
          - "Troubleshooting commands:"
          - "oc get svc {{ vm_name }}-service -n {{ vm_namespace }}"
          - "oc get endpoints {{ vm_name }}-service -n {{ vm_namespace }}"
          - "oc get route {{ vm_name }}-route -n {{ vm_namespace }}"
          - "curl -k https://{{ route_info.resources[0].spec.host | default('') }}"
