---
- hosts: localhost
  gather_facts: false

  vars:
    default_vm_name: "apache-vm"
    default_vm_namespace: "vm-migration-test"
    retries: 10
    delay: 5

  tasks:

    - name: Set effective VM name and namespace
      set_fact:
        vm_name: "{{ vm_name | default(default_vm_name) }}"
        vm_namespace: "{{ vm_namespace | default(default_vm_namespace) }}"

    - name: Wait for VMI to exist
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vmi_info
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: (vmi_info.resources | length) > 0

    - name: Fail if VMI does not exist
      fail:
        msg: "❌ VMI '{{ vm_name }}' not found in namespace '{{ vm_namespace }}'."
      when: (vmi_info.resources | length) == 0

    - name: Fetch first IPv4 address from VMI interfaces
      set_fact:
        vm_ipv4: >-
          {{
            (vmi_info.resources[0].status.interfaces
            | selectattr('ip', 'defined')
            | map(attribute='ip')
            | select('match', '^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$')
            | list
            | first)
            | default('N/A')
          }}

    - name: Fail if no IPv4 found
      fail:
        msg: "❌ No IPv4 address found for VM '{{ vm_name }}'."
      when: vm_ipv4 == 'N/A'

    - name: Display VMI info
      debug:
        msg: "✅ VMI '{{ vm_name }}' IPv4: {{ vm_ipv4 }}"

    - name: Create Service for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            selector:
              vm.kubevirt.io/name: "{{ vm_name }}"
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP

    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Wait for Route to be admitted
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_info
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: (route_info.resources | length) > 0 and (route_info.resources[0].spec.host is defined)

    - name: Get Route status details
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_status

    - name: Display deployment information
      debug:
        msg:
          - "==================================================================="
          - "✅ Henogez WebServer Route Created Successfully!"
          - "==================================================================="
          - " Internal VM IP: http://{{ vm_ipv4 }}"
          - " Internal Service: http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - " External URL (HTTPS): https://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - " External URL (HTTP - will redirect): http://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "-------------------------------------------------------------------"
          - " VM Name: {{ vm_name }}"
          - " Namespace: {{ vm_namespace }}"
          - " Service: {{ vm_name }}-service"
          - " Route: {{ vm_name }}-route"
          - " ✅ Route Status: Admitted: {{ (route_status.resources | default([{}]))[0].status.ingress[0].conditions[0].status | default('Unknown') }}"
          - "==================================================================="
