---
- hosts: localhost
  gather_facts: false

  vars:
    # ✅ Define clean defaults without self-reference
    default_vm_name: "apache-vm"
    default_vm_namespace: "vm-migration-test"

  tasks:

    # ✅ Set VM name and namespace safely
    - name: Set effective VM name and namespace
      set_fact:
        vm_name: "{{ vm_name | default(default_vm_name) }}"
        vm_namespace: "{{ vm_namespace | default(default_vm_namespace) }}"

    - name: Get VM information
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vm_info
      ignore_errors: yes

    - name: Fail if VM does not exist
      fail:
        msg: "❌ VM '{{ vm_name }}' not found in namespace '{{ vm_namespace }}'."
      when: (vm_info.resources | default([])) | length == 0

    - name: Display VM labels for debugging
      debug:
        msg: "VM Labels: {{ (vm_info.resources | default([{}]))[0].metadata.labels | default({}) }}"
      when: (vm_info.resources | default([])) | length > 0

    # ✅ Fetch VM IPv4 from first interface with IPv4 (eth0)
    - name: Fetch VM IPv4 from first interface with IPv4
      set_fact:
        vm_ipv4: "{{ (vm_info.resources[0].status.interfaces | selectattr('name','equalto','eth0') | list)[0].ip }}"
      when: (vm_info.resources | length > 0) and (vm_info.resources[0].status.interfaces is defined)
      ignore_errors: yes

    - name: Display fetched VM IPv4
      debug:
        msg: "Fetched VM IPv4 is {{ vm_ipv4 }}"
      when: vm_ipv4 is defined

    # ✅ Create Service for Apache VM
    - name: Create Service for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            selector:
              vm.kubevirt.io/name: "{{ vm_name }}"
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP

    - name: Verify Service endpoints
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Endpoints
        name: "{{ vm_name }}-service"
        namespace: "{{ vm_namespace }}"
      register: service_endpoints

    - name: Display Service endpoint status
      debug:
        msg: "Service Endpoints: {{ (service_endpoints.resources | default([{}]))[0].subsets | default([]) }}"
      when:
        - (service_endpoints.resources | default([])) | length > 0
        - (service_endpoints.resources[0].subsets is defined)
        - (service_endpoints.resources[0].subsets | length > 0)

    - name: Display warning if no endpoints found
      debug:
        msg: "⚠ Warning: No endpoints found! Check if VM selector matches."
      when:
        - (service_endpoints.resources | default([])) | length == 0 or
          service_endpoints.resources[0].subsets is not defined or
          service_endpoints.resources[0].subsets | length == 0

    # ✅ Create Route for Apache VM
    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Wait for Route to be ready
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_info
      until: (route_info.resources | default([{}]))[0].spec.host is defined
      retries: 10
      delay: 2

    - name: Get Route status details
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_status

    # ✅ Display deployment information with VM IPv4
    - name: Display deployment information
      debug:
        msg:
          - "==========================================================================="
          - "✅ Henogez WebServer Route Created Successfully!"
          - "==========================================================================="
          - "   Access your web server at:"
          - "   External URL (HTTPS): https://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "   External URL (HTTP - will redirect): http://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "   Internal VM IP: http://{{ vm_ipv4 | default('N/A') }}"
          - "   Internal Service: http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - "   Resource Details:"
          - "   VM Name: {{ vm_name }}"
          - "   Namespace: {{ vm_namespace }}"
          - "   Service: {{ vm_name }}-service"
          - "   Route: {{ vm_name }}-route"
          - "   Route Status: Admitted: {{ (route_status.resources | default([{}]))[0].status.ingress[0].conditions[0].status | default('Unknown') }}"
          - "==========================================================================="
