---
- name: Create Route and Fetch VM URLs
  hosts: localhost
  gather_facts: false
  environment:
    KUBECONFIG: /etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/localhost.kubeconfig
  vars:
    vm_name: apache-vm
    vm_namespace: vm-migration-test
    service_name: "{{ vm_name }}-service"
    route_name: "{{ vm_name }}-route"
    retries: 5
    delay: 10

  tasks:

    - name: Get internal service ClusterIP
      command: "oc get svc {{ service_name }} -n {{ vm_namespace }} -o jsonpath='{.spec.clusterIP}'"
      register: internal_ip
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: internal_ip.stdout != ""

    - name: Get external route host
      command: "oc get route {{ route_name }} -n {{ vm_namespace }} -o jsonpath='{.spec.host}'"
      register: external_route
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: external_route.stdout != ""

    - name: Display internal and external URLs
      debug:
        msg:
          - "Internal Service URL: http://{{ internal_ip.stdout }}"
          - "External Route URL: https://{{ external_route.stdout }}"
