---
- hosts: localhost
  gather_facts: no
  vars:
    vm_name: apache-vm
    vm_namespace: vm-migration-test
    kubeconfig_path: /etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/lb-int.kubeconfig

  tasks:
    - name: Verify kubeconfig path exists
      stat:
        path: "{{ kubeconfig_path }}"
      register: kubeconfig_stat

    - name: Fail if kubeconfig file not found
      fail:
        msg: "KUBECONFIG not found at {{ kubeconfig_path }}. Please verify the file path."
      when: not kubeconfig_stat.stat.exists

    - name: Get VM information
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
        kubeconfig: "{{ kubeconfig_path }}"
      register: vm_info
      ignore_errors: yes

    - name: Display VM labels for debugging
      debug:
        msg: "VM Labels: {{ vm_info.resources[0].metadata.labels }}"
      when: vm_info.resources | length > 0

    - name: Create Service for Apache VM
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            selector:
              vm.kubevirt.io/name: "{{ vm_name }}"
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP

    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Wait for Route to be ready
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
        kubeconfig: "{{ kubeconfig_path }}"
      register: route_info
      until: route_info.resources | length > 0 and route_info.resources[0].spec.host is defined
      retries: 10
      delay: 3

    - name: Display internal and external route URLs
      debug:
        msg:
          - "=============================================================="
          - "Internal URL:  http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - "External URL:  https://{{ route_info.resources[0].spec.host }}"
          - "=============================================================="
