---
- name: Create a VM on OpenShift Virtualization and extract IPv4
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    vm_name: apache-vm
    vm_project: vm-migration-test
    storage_class: nfs-storage-class
    storage_size: 15Gi
    memory_size: 2Gi
    cpu_cores: 2
    cpu_sockets: 1
    cpu_threads: 1
    cloud_init_password: password
    ssh_timeout: 300
    network_attachment: br-ex-network
    ip_wait_time: 30

  tasks:
    - name: Display VM configuration
      debug:
        msg:
          - "Creating VM: {{ vm_name }}"
          - "Namespace: {{ vm_project }}"
          - "Memory: {{ memory_size }}"
          - "CPU Cores: {{ cpu_cores }}"
          - "Storage Class: {{ storage_class }}"
          - "Network: {{ network_attachment }}"

    - name: Provision Virtual Machine in OpenShift
      kubernetes.core.k8s:
        state: present
        validate_certs: no
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ vm_project }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            running: true
            dataVolumeTemplates:
              - metadata:
                  name: "{{ vm_name }}"
                  annotations:
                    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
                spec:
                  source:
                    pvc:
                      name: centos9-golden-image
                      namespace: vm-migration-test
                  storage:
                    storageClassName: "{{ storage_class }}"
                    accessModes: [ "ReadWriteMany" ]
                    volumeMode: Filesystem
                    resources:
                      requests:
                        storage: "{{ storage_size }}"
            template:
              metadata:
                labels:
                  kubevirt.io/domain: "{{ vm_name }}"
              spec:
                domain:
                  cpu:
                    cores: "{{ cpu_cores }}"
                    sockets: "{{ cpu_sockets }}"
                    threads: "{{ cpu_threads }}"
                  memory:
                    guest: "{{ memory_size }}"
                  devices:
                    disks:
                      - name: rootdisk
                        disk: { bus: virtio }
                      - name: cloudinitdisk
                        disk: { bus: virtio }
                    interfaces:
                      - name: default
                        bridge: {}
                networks:
                  - name: default
                    multus:
                      networkName: "{{ network_attachment }}"
                volumes:
                  - name: rootdisk
                    dataVolume:
                      name: "{{ vm_name }}"
                  - name: cloudinitdisk
                    cloudInitNoCloud:
                      networkData: |
                        version: 2
                        ethernets:
                          eth0:
                            dhcp4: true
                            dhcp6: false
                      userData: |
                        #cloud-config
                        user: root
                        password: {{ cloud_init_password }}
                        chpasswd: { expire: False }
                        ssh_pwauth: True
                        runcmd:
                          - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
                          - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
                          - systemctl restart sshd
                          - systemctl enable sshd
      register: vm_creation

    - name: Wait for DataVolume to be ready
      kubernetes.core.k8s_info:
        api_version: cdi.kubevirt.io/v1beta1
        kind: DataVolume
        name: "{{ vm_name }}"
        namespace: "{{ vm_project }}"
        validate_certs: no
      register: dv_info
      until:
        - dv_info.resources is defined
        - dv_info.resources | length > 0
        - dv_info.resources[0].status.phase == "Succeeded"
      retries: 30
      delay: 10

    - name: Wait for VM to be running
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_project }}"
        validate_certs: no
      register: vmi_info
      until:
        - vmi_info.resources is defined
        - vmi_info.resources | length > 0
        - vmi_info.resources[0].status.phase == "Running"
      retries: 30
      delay: 10

    - name: Pause for IP assignment
      pause:
        seconds: "{{ ip_wait_time }}"

    - name: Get latest VM network info
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ vm_name }}"
        namespace: "{{ vm_project }}"
        validate_certs: no
      register: vmi_network_info

    - name: Debug - Show all interfaces
      debug:
        var: vmi_network_info.resources[0].status.interfaces

    - name: Extract IPv4 address safely from all interfaces
      set_fact:
        all_ip_addresses: >-
          {{
            vmi_network_info.resources[0].status.interfaces
            | map('extract', 'ipAddresses')
            | select('defined')
            | map('flatten')
            | flatten
            | list
          }}
        ipv4_candidates: "{{ all_ip_addresses | select('match', '^(\\d{1,3}\\.){3}\\d{1,3}$') | list }}"
        vm_ip: "{{ (ipv4_candidates | first) | default('No IPv4 assigned') }}"
      when:
        - vmi_network_info.resources is defined
        - vmi_network_info.resources | length > 0
        - vmi_network_info.resources[0].status.interfaces is defined
        - vmi_network_info.resources[0].status.interfaces | length > 0

    - name: Display IPv4 extraction result
      debug:
        msg:
          - "======================================"
          - "VM Name: {{ vm_name }}"
          - "All IPs Detected: {{ all_ip_addresses | join(', ') | default('None') }}"
          - "IPv4 Addresses: {{ ipv4_candidates | join(', ') | default('None detected') }}"
          - "Selected IPv4: {{ vm_ip }}"
          - "======================================"

    - name: Fail if IPv4 is missing
      fail:
        msg: |
          No IPv4 address detected for {{ vm_name }}.
          Verify that DHCP is enabled and the Multus network ({{ network_attachment }}) provides IPv4.
      when: ipv4_candidates | length == 0

    - name: Save IPv4 for downstream jobs
      set_stats:
        data:
          vm_ip: "{{ vm_ip }}"
          vm_name: "{{ vm_name }}"
          vm_project: "{{ vm_project }}"
        per_host: no

    - name: Deployment Summary
      debug:
        msg:
          - "======================================"
          - "VM Deployment Complete Successfully!"
          - "VM Name: {{ vm_name }}"
          - "IPv4 Address: {{ vm_ip }}"
          - "Username: root"
          - "Password: {{ cloud_init_password }}"
          - "Network: {{ network_attachment }}"
          - "======================================"
