---
- hosts: localhost
  gather_facts: no
  vars:
    vm_name: apache-vm
    vm_namespace: vm-migration-test
    kubeconfig_path: /etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/lb-ext.kubeconfig

  tasks:
    - name: Ensure KUBECONFIG is exported
      ansible.builtin.set_env:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Get VM information
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vm_info
      ignore_errors: yes

    - name: Display VM labels for debugging
      debug:
        msg: "VM Labels: {{ vm_info.resources[0].metadata.labels | default('No labels found') }}"
      when: vm_info.resources | length > 0

    - name: Create Service for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            selector:
              vm.kubevirt.io/name: "{{ vm_name }}"
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP

    - name: Verify Service endpoints
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Endpoints
        name: "{{ vm_name }}-service"
        namespace: "{{ vm_namespace }}"
      register: service_endpoints

    - name: Display Service endpoint status
      debug:
        msg: 
          - "Service Endpoints: {{ service_endpoints.resources[0].subsets | default([]) }}"
      when: 
        - service_endpoints.resources | length > 0
        - service_endpoints.resources[0].subsets is defined
        - service_endpoints.resources[0].subsets | length > 0

    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Wait for Route to be ready
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_info
      until: route_info.resources[0].spec.host is defined
      retries: 10
      delay: 3

    - name: Display Route and Access Information
      debug:
        msg:
          - "================================================================================"
          - " Web Server Route Created Successfully!"
          - "================================================================================"
          - " ✅ Access your Apache web server from your browser:"
          - ""
          - " 🌐 External Route (HTTPS):  https://{{ route_info.resources[0].spec.host }}"
          - " 🌐 External Route (HTTP):   http://{{ route_info.resources[0].spec.host }}"
          - ""
          - " 🧩 Internal Service URL:"
          - "     http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - ""
          - " Namespace: {{ vm_namespace }}"
          - " Service:   {{ vm_name }}-service"
          - " Route:     {{ vm_name }}-route"
          - ""
          - " Troubleshooting Commands:"
          - "   oc get svc {{ vm_name }}-service -n {{ vm_namespace }}"
          - "   oc get endpoints {{ vm_name }}-service -n {{ vm_namespace }}"
          - "   oc get route {{ vm_name }}-route -n {{ vm_namespace }}"
          - "   curl -k https://{{ route_info.resources[0].spec.host }}"
          - "================================================================================"
