---
- name: Configure VM network and create OpenShift route
  hosts: localhost
  gather_facts: false

  vars:
    default_vm_name: "apache-vm"
    default_vm_namespace: "vm-migration-test"
    vm_ip: "10.0.0.107"  # override at runtime
    vm_user: "root"
    vm_password: "password"

  tasks:

    - name: Set effective VM name and namespace
      set_fact:
        vm_name: "{{ vm_name | default(default_vm_name) }}"
        vm_namespace: "{{ vm_namespace | default(default_vm_namespace) }}"

    - name: Add VM to dynamic inventory
      add_host:
        name: "{{ vm_name }}"
        ansible_host: "{{ vm_ip }}"
        ansible_user: "{{ vm_user }}"
        ansible_password: "{{ vm_password }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        groups: dynamic_vms

- hosts: dynamic_vms
  gather_facts: yes
  become: yes

  tasks:
    - name: Delete old eth0 connection if exists
      command: nmcli con delete eth0
      ignore_errors: yes

    - name: Create persistent static eth0 network
      command: >
        nmcli connection add type ethernet autoconnect yes con-name eth0 ifname eth0
        ipv4.addresses {{ vm_ip }}/24
        ipv4.gateway 10.0.0.1
        ipv4.dns 10.0.0.17,8.8.8.8
        ipv4.dns-search ocp4.henogez.com
        ipv4.method manual
      ignore_errors: no

    - name: Bring up eth0 connection
      command: nmcli connection up eth0

    - name: Restart NetworkManager to apply changes
      systemd:
        name: NetworkManager
        state: restarted

- hosts: localhost
  gather_facts: false

  tasks:
    - name: Create Service for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ vm_name }}-service"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            selector:
              vm.kubevirt.io/name: "{{ vm_name }}"
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP

    - name: Create Route for Apache VM
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: "{{ vm_name }}-route"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_name }}"
          spec:
            to:
              kind: Service
              name: "{{ vm_name }}-service"
              weight: 100
            port:
              targetPort: http
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None

    - name: Wait for Route to be ready
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: "{{ vm_name }}-route"
        namespace: "{{ vm_namespace }}"
      register: route_info
      until: (route_info.resources | default([{}]))[0].spec.host is defined
      retries: 10
      delay: 5

    - name: Display deployment information
      debug:
        msg:
          - "==========================================================================="
          - "✅ Henogez WebServer Route Created Successfully!"
          - "==========================================================================="
          - "   External URL (HTTPS): https://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "   External URL (HTTP - will redirect): http://{{ (route_info.resources | default([{}]))[0].spec.host | default('N/A') }}"
          - "   Internal Service: http://{{ vm_name }}-service.{{ vm_namespace }}.svc.cluster.local"
          - "   VM Name: {{ vm_name }}"
          - "   Namespace: {{ vm_namespace }}"
          - "   Service: {{ vm_name }}-service"
          - "   Route: {{ vm_name }}-route"
          - "==========================================================================="
