---
- name: Create Route and Fetch VM Details
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: apache-vm
    vm_namespace: vm-migration-test
    service_name: apache-vm-service
    route_name: apache-vm-route
    retries: 10
    delay: 6
    kubeconfig_path: /etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/localhost.kubeconfig

  tasks:

    - name: Ensure KUBECONFIG is set
      set_fact:
        kube_env:
          KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Get VM information
      command: >
        oc get vm {{ vm_name }} -n {{ vm_namespace }} -o json
      register: vm_info
      failed_when: vm_info.rc != 0
      environment: "{{ kube_env }}"

    - name: Get VMI information
      command: >
        oc get vmi {{ vm_name }} -n {{ vm_namespace }} -o json
      register: vmi_info
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: vmi_info.rc == 0
      environment: "{{ kube_env }}"

    - name: Fetch VM IP (first IPv4) from VMI JSON
      set_fact:
        vm_ip: "{{ (vmi_info.stdout | from_json).status.interfaces[0].ip }}"
      when: vmi_info.stdout is defined

    - name: Ensure Route exists
      command: >
        oc apply -f - <<EOF
        apiVersion: route.openshift.io/v1
        kind: Route
        metadata:
          name: {{ route_name }}
          namespace: {{ vm_namespace }}
        spec:
          to:
            kind: Service
            name: {{ service_name }}
          port:
            targetPort: http
          tls:
            termination: edge
        EOF
      environment: "{{ kube_env }}"

    - name: Wait for route to be admitted
      command: >
        oc get route {{ route_name }} -n {{ vm_namespace }} -o jsonpath='{.status.ingress[0].conditions[?(@.type=="Admitted")].status}'
      register: route_status
      retries: "{{ retries }}"
      delay: "{{ delay }}"
      until: route_status.stdout == "True"
      environment: "{{ kube_env }}"

    - name: Fetch Route hostname
      command: >
        oc get route {{ route_name }} -n {{ vm_namespace }} -o jsonpath='{.spec.host}'
      register: route_hostname
      environment: "{{ kube_env }}"

    - name: Display VM and Route info
      debug:
        msg:
          - "External URL (HTTPS): https://{{ route_hostname.stdout }}"
          - "External URL (HTTP - will redirect): http://{{ route_hostname.stdout }}"
          - "-------------------------------------------------------------------"
          - "VM Name: {{ vm_name }}"
          - "Namespace: {{ vm_namespace }}"
          - "Service: {{ service_name }}"
          - "Route: {{ route_name }}"
          - "✅ Route Status: Admitted: True"
          - "Internal VM IP: http://{{ vm_ip }}"
          - "Internal Service: http://{{ service_name }}.{{ vm_namespace }}.svc.cluster.local"
          - "==================================================================="
