---
- hosts: vms
  gather_facts: yes
  become: yes

  tasks:
    - name: Disable SELinux
      replace:
        path: /etc/selinux/config
        regexp: 'SELINUX=enforcing'
        replace: 'SELINUX=disabled'

    - name: Disable IPv6
      lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
        state: present
      loop:
        - net.ipv6.conf.all.disable_ipv6 = 1
        - net.ipv6.conf.default.disable_ipv6 = 1

    - name: Reload sysctl
      command: sysctl -p

    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - wget
        - telnet
        - nc
        - rsyslog
        - net-tools
        - bind-utils
        - unzip
        - traceroute
        - lsof
        - psmisc
        - yum-utils
        - java-11-openjdk-devel

    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Reboot the VM
      reboot:
        reboot_timeout: 300
        test_command: uptime
