- name: Prepare VM inventory if running standalone
  hosts: localhost
  gather_facts: false
  vars:
    cloud_init_password: password
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  tasks:
    - name: Add VM to dynamic inventory if vm_ip is passed
      add_host:
        name: apache-vm
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: "{{ cloud_init_password }}"
        ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"
        groups: dynamic_vms
      when: vm_ip is defined

- hosts: dynamic_vms
  gather_facts: yes
  become: yes

  tasks:
    - name: Disable SELinux
      replace:
        path: /etc/selinux/config
        regexp: 'SELINUX=enforcing'
        replace: 'SELINUX=disabled'

    - name: Disable IPv6
      lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
        state: present
      loop:
        - net.ipv6.conf.all.disable_ipv6 = 1
        - net.ipv6.conf.default.disable_ipv6 = 1

    - name: Reload sysctl
      command: sysctl -p

    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - wget
        - telnet
        - nc
        - rsyslog
        - net-tools
        - bind-utils
        - unzip
        - traceroute
        - lsof
        - psmisc
        - yum-utils
        - java-11-openjdk-devel

    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Reboot the VM
      reboot:
        reboot_timeout: 300
        test_command: uptime
