---
- hosts: localhost
  gather_facts: no
  vars:
    vm_password: "{{ cloud_init_password | default('password') }}"
    vm_ip: "{{ vm_ip | default(omit) }}"
    rhel_username: "info@pacetechsystems.com"
    rhel_password: "Silverado@8787!!!!"

  tasks:
    - name: Fail if vm_ip is undefined
      fail:
        msg: "vm_ip is not defined. Make sure the wait_for_ssh playbook ran successfully."
      when: vm_ip is not defined

    - name: Add VM to dynamic inventory
      add_host:
        name: target_vm_host
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: "{{ vm_password }}"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        groups: vms

    - name: Display VM inventory info
      debug:
        msg: "VM {{ vm_ip }} added to dynamic group 'vms' for post-installation tasks"

- hosts: vms
  gather_facts: no
  vars:
    rhel_username: "<YOUR_RH_USERNAME>"
    rhel_password: "Silverado@8787!!!!"

  tasks:
    - name: Disable SELinux on RHEL/CentOS
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=enforcing'
        replace: 'SELINUX=disabled'

    - name: Disable IPv6
      lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
        state: present
      loop:
        - net.ipv6.conf.all.disable_ipv6 = 1
        - net.ipv6.conf.default.disable_ipv6 = 1

    - name: Apply sysctl changes
      command: sysctl -p

    - name: Register RHEL subscription
      shell: |
        subscription-manager register --username={{ rhel_username }} --password={{ rhel_password }} --auto-attach
      register: rh_subscribe
      ignore_errors: yes

    - name: Enable required RHEL repos
      shell: |
        subscription-manager repos \
          --enable=rhel-9-for-x86_64-baseos-rpms \
          --enable=rhel-9-for-x86_64-appstream-rpms
      when: rh_subscribe is succeeded
      ignore_errors: yes

    - name: Install software packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - wget
        - telnet
        - nc
        - rsyslog
        - net-tools
        - bind-utils
        - unzip
        - traceroute
        - lsof
        - psmisc
        - yum-utils
        - java-11-openjdk-devel

    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Reboot VM
      reboot:
        reboot_timeout: 3000
        test_command: "uptime"

    - name: Confirm reboot
      wait_for_connection:
        timeout: 300
