---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Load vm_ip from temporary file
      set_fact:
        vm_ip: "{{ lookup('file', '/tmp/vm_ip.txt') }}"

    - name: Fail if vm_ip is not defined
      fail:
        msg: "❌ vm_ip is not defined. Make sure wait_for_ssh.yml ran successfully."
      when: vm_ip == "" or vm_ip is not defined

- hosts: vms
  gather_facts: false
  tasks:
    - name: Disable SELinux
      replace:
        path: /etc/selinux/config
        regexp: 'SELINUX=enforcing'
        replace: 'SELINUX=disabled'

    - name: Disable IPv6
      lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
        state: present
      loop:
        - net.ipv6.conf.all.disable_ipv6 = 1
        - net.ipv6.conf.default.disable_ipv6 = 1

    - name: Reload sysctl
      command: sysctl -p

    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - wget
        - telnet
        - nc
        - rsyslog
        - net-tools
        - bind-utils
        - unzip
        - traceroute
        - lsof
        - psmisc
        - yum-utils
        - java-11-openjdk-devel

    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Reboot the VM
      reboot:
        reboot_timeout: 300
        test_command: uptime
