---
- name: Wait for VM IPv4 and SSH readiness
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: apache-vm
    vm_project: vm-migration-test
    cloud_init_password: password
    max_ip_wait: 300       # total time to wait for IP
    ip_poll_interval: 10   # seconds between polls
    ssh_timeout: 300       # seconds for SSH wait
    ansible_ssh_common_args: '-o AddressFamily=inet -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:

    - name: Poll VM for IPv4 address
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ vm_project }}"
        name: "{{ vm_name }}"
        validate_certs: no
      register: vmi_info
      until: 
        - vmi_info.resources | length > 0
        - vmi_info.resources[0].status.interfaces[0].ipAddress is defined
      retries: "{{ max_ip_wait // ip_poll_interval }}"
      delay: "{{ ip_poll_interval }}"

    - name: Set VM IP fact
      set_fact:
        vm_ip: "{{ vmi_info.resources[0].status.interfaces[0].ipAddress }}"

    - name: Wait for SSH port 22 to be available
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        timeout: "{{ ssh_timeout }}"
        state: started

    - name: Confirm VM IPv4 and SSH readiness
      debug:
        msg:
          - "✅ VM IPv4 detected: {{ vm_ip }}"
          - "✅ SSH port 22 is reachable on {{ vm_ip }}"

    - name: Add VM to dynamic in-memory inventory
      add_host:
        name: "target_vm_host"
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: "{{ cloud_init_password }}"
        ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"
        groups: vms

    - name: Display added VM info
      debug:
        msg: "VM {{ vm_name }} ({{ vm_ip }}) added to dynamic group 'vms' for next tasks"
