- name: Wait for VM IPv4, configure network, and register repos
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: apache-vm
    vm_project: vm-migration-test
    cloud_init_password: password
    vm_gateway: "10.0.0.1"
    vm_dns: "8.8.8.8"
    rhsm_username: "info@pacetechsystems.com"
    rhsm_password: "Silverado@8787!!!!"
    rhel_version: 9
    max_ip_wait: 300
    ip_poll_interval: 10
    ssh_timeout: 300
    ansible_ssh_common_args: '-o AddressFamily=inet -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:

    - name: Poll VM for IPv4 address
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ vm_project }}"
        name: "{{ vm_name }}"
        validate_certs: no
      register: vmi_info
      until: 
        - vmi_info.resources | length > 0
        - vmi_info.resources[0].status.interfaces[0].ipAddress is defined
      retries: "{{ max_ip_wait // ip_poll_interval }}"
      delay: "{{ ip_poll_interval }}"

    - name: Set VM IP fact
      set_fact:
        vm_ip: "{{ vmi_info.resources[0].status.interfaces[0].ipAddress }}"

    - name: Wait for SSH port 22 to be available
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        timeout: "{{ ssh_timeout }}"
        state: started

    - name: Add VM to dynamic inventory
      add_host:
        name: "{{ vm_name }}"
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: "{{ cloud_init_password }}"
        ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"
        groups: vms
        vm_gateway: "{{ vm_gateway }}"
        vm_dns: "{{ vm_dns }}"
        rhsm_username: "{{ rhsm_username }}"
        rhsm_password: "{{ rhsm_password }}"
        rhel_version: "{{ rhel_version }}"

- name: Configure network, register VM, and enable RHEL repositories
  hosts: vms
  become: true
  gather_facts: true

  vars:
    registration_retries: 3
    registration_delay: 10

  tasks:
    - name: Ensure NetworkManager is installed
      package:
        name: NetworkManager
        state: present

    # ... rest of your add-repo tasks here ...
