---
- name: Wait for VM SSH and add to inventory
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ssh_timeout: 300
    vm_password: "{{ cloud_init_password | default('password') }}"
    ansible_ssh_common_args: '-o AddressFamily=inet -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:
    - name: Display VM variables
      debug:
        msg:
          - "VM Name: {{ vm_name }}"
          - "VM IP: {{ vm_ip }}"
          - "VM Project: {{ vm_project }}"

    - name: Wait for SSH to become available
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        delay: 10
        timeout: "{{ ssh_timeout }}"
        state: started
      vars:
        ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"

    - name: Add VM to in-memory inventory
      add_host:
        name: "target_vm_host"
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: "{{ vm_password }}"
        ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"
        groups: vms

    - name: Debug inventory addition
      debug:
        msg: "VM {{ vm_name }} ({{ vm_ip }}) added to group 'vms'"
