---
- name: Wait for VM IPv4 and SSH readiness
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    vm_name: apache-vm
    vm_project: vm-migration-test
    ssh_timeout: 10        # per SSH probe attempt
    max_wait: 600          # total wait time in seconds
    poll_interval: 10
    vm_password: "{{ cloud_init_password | default('password') }}"
    ansible_ssh_common_args: '-o AddressFamily=inet -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:

    - name: Wait for VM IPv4 to appear
      retries: "{{ (max_wait // poll_interval) | int }}"
      delay: "{{ poll_interval }}"
      until: vm_ip is defined and vm_ip != ''
      block:
        - name: Get VM interface info
          kubernetes.core.k8s_info:
            api_version: kubevirt.io/v1
            kind: VirtualMachineInstance
            namespace: "{{ vm_project }}"
            name: "{{ vm_name }}"
            validate_certs: no
          register: vmi_info
          ignore_errors: true

        - name: Extract IPv4 from guest agent
          set_fact:
            vm_ip: >-
              {{ (vmi_info.resources[0].status.interfaces[0].ipAddress | default('')) 
                 | regex_search('^([0-9]{1,3}\\.){3}[0-9]{1,3}', '\\0') }}
          when:
            - vmi_info.resources is defined
            - vmi_info.resources | length > 0
            - vmi_info.resources[0].status.interfaces is defined
            - vmi_info.resources[0].status.interfaces[0].ipAddress is defined
          ignore_errors: true

    - name: Wait for SSH port 22 to be ready
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        timeout: "{{ ssh_timeout }}"
        state: started
      register: ssh_probe
      retries: "{{ (max_wait // ssh_timeout) | int }}"
      delay: "{{ poll_interval }}"

    - name: Add VM to dynamic inventory
      add_host:
        name: "target_vm_host"
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: "{{ vm_password }}"
        ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"
        groups: vms

    - name: Confirm VM IPv4 and SSH readiness
      debug:
        msg:
          - "✅ VM IPv4 detected: {{ vm_ip }}"
          - "✅ SSH port 22 reachable on {{ vm_ip }}"
