---
- name: Wait for VM to report IPv4 and SSH readiness
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: apache-vm
    vm_project: vm-migration-test
    cloud_init_password: password
    max_ip_wait: 300
    ip_poll_interval: 10
    ssh_timeout: 300
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:
    - name: Poll VM until IPv4 is available
      vars:
        vm_ip: ""
        attempt: 0
      until: vm_ip != ""
      retries: "{{ max_ip_wait // ip_poll_interval }}"
      delay: "{{ ip_poll_interval }}"
      block:
        - name: Get VM interface info
          kubernetes.core.k8s_info:
            api_version: kubevirt.io/v1
            kind: VirtualMachineInstance
            namespace: "{{ vm_project }}"
            name: "{{ vm_name }}"
            validate_certs: no
          register: vmi_info
          ignore_errors: true

        - name: Extract IPv4 if available
          set_fact:
            vm_ip: >-
              {{ vmi_info.resources[0].status.interfaces[0].ipAddress
                 | regex_search('^([0-9]{1,3}\.){3}[0-9]{1,3}', '\\0') }}
          when:
            - vmi_info.resources is defined
            - vmi_info.resources | length > 0
            - vmi_info.resources[0].status.interfaces is defined
            - vmi_info.resources[0].status.interfaces[0].ipAddress is defined
          ignore_errors: true

    - name: Wait for SSH port 22 to be available
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        timeout: "{{ ssh_timeout }}"
        state: started

    - name: Add VM to dynamic inventory
      add_host:
        name: target_vm
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: "{{ cloud_init_password }}"
        ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"
        groups: vms

    - name: Save VM IP to temporary fact file
      copy:
        content: "{{ vm_ip }}"
        dest: /tmp/vm_ip.txt

    - name: Display VM IP
      debug:
        msg: "✅ VM {{ vm_name }} IPv4 is {{ vm_ip }} and SSH is reachable"
