---
- name: Wait for VM to have IPv4 and SSH readiness
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    vm_project: "vm-migration-test"      # VM namespace/project
    vm_name: "apache-vm"                 # VM name
    cloud_init_password: "password"      # VM root password
    max_ip_wait: 300                      # Max seconds to wait for IPv4
    ip_poll_interval: 10                  # Polling interval in seconds
    ssh_timeout: 300                      # SSH wait timeout
    ansible_ssh_common_args: '-o AddressFamily=inet -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:

    - name: Poll VM until IPv4 is available
      block:
        - name: Get VM interface info
          kubernetes.core.k8s_info:
            api_version: kubevirt.io/v1
            kind: VirtualMachineInstance
            namespace: "{{ vm_project }}"
            name: "{{ vm_name }}"
            validate_certs: no
          register: vmi_info
          ignore_errors: true

        - name: Extract IPv4 if available
          set_fact:
            vm_ip: >-
              {{ vmi_info.resources[0].status.interfaces[0].ipAddress
                 | regex_search('^([0-9]{1,3}\\.){3}[0-9]{1,3}', '\\0') }}
          when:
            - vmi_info.resources is defined
            - vmi_info.resources | length > 0
            - vmi_info.resources[0].status.interfaces is defined
            - vmi_info.resources[0].status.interfaces[0].ipAddress is defined
      retries: "{{ (max_ip_wait // ip_poll_interval) | int }}"
      delay: "{{ ip_poll_interval }}"
      until: vm_ip is defined and vm_ip != ''

    - name: Wait for SSH port 22 to be available on the VM
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        timeout: "{{ ssh_timeout }}"
        state: started

    - name: Add VM to dynamic in-memory inventory
      add_host:
        name: "target_vm_host"
        ansible_host: "{{ vm_ip }}"
        ansible_user: root
        ansible_password: "{{ cloud_init_password }}"
        ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"
        groups: vms

    - name: Display VM connectivity summary
      debug:
        msg:
          - "✅ VM {{ vm_name }} IPv4 detected: {{ vm_ip }}"
          - "✅ SSH port 22 is reachable on {{ vm_ip }}"
          - "✅ VM added to dynamic group 'vms' for further tasks"
